server:
  http1_port: "8080"
  http2_port: "8443"
  grpc_port: "19090"
  xds_port: "19091"
  host: "localhost"

etcd:
  endpoints:
  - "https://etcd:2379"
  dial_timeout: "5s"
  tls:
    enabled: true
    cert_file: "./secrets/certs/etcd/client.pem"
    key_file: "./secrets/certs/etcd/client-key.pem"
    ca_file: "./secrets/certs/etcd/ca.pem"

# Tenant identifier for this controller
tenant: "dev-cluster"

# API Server configuration (optional)
# If enabled, controller will register with API Server and receive snapshots via stream
# If disabled, controller will use local Git repositories
api_server:
  enabled: true
  address: "gateway-api-server:19093"

repositories:
# Remote Git repository
- name: api-gateway-schemas-https
  source: git
  url: "https://github.com/MikhailMinaev/api-gateway-schemas.git"
  auth:
    type: "token"
    token_env: "GITHUB_ACCESS_TOKEN"

# Local Git repository
- name: api-gateway-schemas-local-git-repo
  source: local-git
  path: "/app/local-dir"

# Local directory without Git
- name: api-gateway-schemas-local-dir
  source: local-dir
  path: "/app/local-dir"
    # - name: api-gateway-schemas-ssh
    #   url: "git@github.com:MikhailMinaev/api-gateway-schemas.git"
    #   auth:
    #     type: "ssh"
    #     ssh_key_path: "./secrets/keys/api-schemas-ed25519"
    # ssh_key_env: "SSH_PRIVATE_KEY"

environments:
- name: prod
  bundles:
    static:
    - name: api-gateway-schemas
      repository: api-gateway-schemas-https
      ref: tags/v0.0.1
      path: openapi
  services:
    static:
    - name: be-service-01
      upstream: "http://mock-be-service-01-prod:8080"
    - name: be-service-02
      upstream: "http://mock-be-service-02-prod:8080"

services:
  static:
  - name: be-service-03
    upstream: "http://mock-be-service-03:8080"
