server:
  http1_port: "8080"
  http2_port: "8443"
  grpc_port: "19090"
  xds_port: "19091"
  host: "localhost"

etcd:
  endpoints:
  - "https://etcd-controller-dev:2379"
  dial_timeout: "5s"
  tls:
    enabled: true
    cert_file: "./secrets/certs/etcd/client.pem"
    key_file: "./secrets/certs/etcd/client-key.pem"
    ca_file: "./secrets/certs/etcd/ca.pem"

tenant: "dev-cluster"

# gRPC address of API Server (ControllerRegistry / snapshot stream)
api_server:
  address: "gateway-api-server:19093"

environments:

services:
  static:
  - name: be-service-03
    upstream: "http://mock-be-service-03:8080"
