// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: merionyx/gateway/controller_registry/v1/controller_registry.proto

package controllerregistryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControllerRegistryService_RegisterController_FullMethodName = "/merionyx.gateway.controller_registry.v1.ControllerRegistryService/RegisterController"
	ControllerRegistryService_StreamSnapshots_FullMethodName    = "/merionyx.gateway.controller_registry.v1.ControllerRegistryService/StreamSnapshots"
	ControllerRegistryService_Heartbeat_FullMethodName          = "/merionyx.gateway.controller_registry.v1.ControllerRegistryService/Heartbeat"
)

// ControllerRegistryServiceClient is the client API for ControllerRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControllerRegistryService service for registration and managing controllers
type ControllerRegistryServiceClient interface {
	RegisterController(ctx context.Context, in *RegisterControllerRequest, opts ...grpc.CallOption) (*RegisterControllerResponse, error)
	StreamSnapshots(ctx context.Context, in *StreamSnapshotsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamSnapshotsResponse], error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type controllerRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerRegistryServiceClient(cc grpc.ClientConnInterface) ControllerRegistryServiceClient {
	return &controllerRegistryServiceClient{cc}
}

func (c *controllerRegistryServiceClient) RegisterController(ctx context.Context, in *RegisterControllerRequest, opts ...grpc.CallOption) (*RegisterControllerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterControllerResponse)
	err := c.cc.Invoke(ctx, ControllerRegistryService_RegisterController_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerRegistryServiceClient) StreamSnapshots(ctx context.Context, in *StreamSnapshotsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamSnapshotsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControllerRegistryService_ServiceDesc.Streams[0], ControllerRegistryService_StreamSnapshots_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSnapshotsRequest, StreamSnapshotsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControllerRegistryService_StreamSnapshotsClient = grpc.ServerStreamingClient[StreamSnapshotsResponse]

func (c *controllerRegistryServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControllerRegistryService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerRegistryServiceServer is the server API for ControllerRegistryService service.
// All implementations must embed UnimplementedControllerRegistryServiceServer
// for forward compatibility.
//
// ControllerRegistryService service for registration and managing controllers
type ControllerRegistryServiceServer interface {
	RegisterController(context.Context, *RegisterControllerRequest) (*RegisterControllerResponse, error)
	StreamSnapshots(*StreamSnapshotsRequest, grpc.ServerStreamingServer[StreamSnapshotsResponse]) error
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedControllerRegistryServiceServer()
}

// UnimplementedControllerRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerRegistryServiceServer struct{}

func (UnimplementedControllerRegistryServiceServer) RegisterController(context.Context, *RegisterControllerRequest) (*RegisterControllerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterController not implemented")
}
func (UnimplementedControllerRegistryServiceServer) StreamSnapshots(*StreamSnapshotsRequest, grpc.ServerStreamingServer[StreamSnapshotsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamSnapshots not implemented")
}
func (UnimplementedControllerRegistryServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControllerRegistryServiceServer) mustEmbedUnimplementedControllerRegistryServiceServer() {
}
func (UnimplementedControllerRegistryServiceServer) testEmbeddedByValue() {}

// UnsafeControllerRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerRegistryServiceServer will
// result in compilation errors.
type UnsafeControllerRegistryServiceServer interface {
	mustEmbedUnimplementedControllerRegistryServiceServer()
}

func RegisterControllerRegistryServiceServer(s grpc.ServiceRegistrar, srv ControllerRegistryServiceServer) {
	// If the following call panics, it indicates UnimplementedControllerRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerRegistryService_ServiceDesc, srv)
}

func _ControllerRegistryService_RegisterController_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterControllerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerRegistryServiceServer).RegisterController(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerRegistryService_RegisterController_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerRegistryServiceServer).RegisterController(ctx, req.(*RegisterControllerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerRegistryService_StreamSnapshots_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSnapshotsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerRegistryServiceServer).StreamSnapshots(m, &grpc.GenericServerStream[StreamSnapshotsRequest, StreamSnapshotsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControllerRegistryService_StreamSnapshotsServer = grpc.ServerStreamingServer[StreamSnapshotsResponse]

func _ControllerRegistryService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerRegistryServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerRegistryService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerRegistryServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerRegistryService_ServiceDesc is the grpc.ServiceDesc for ControllerRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "merionyx.gateway.controller_registry.v1.ControllerRegistryService",
	HandlerType: (*ControllerRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterController",
			Handler:    _ControllerRegistryService_RegisterController_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ControllerRegistryService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSnapshots",
			Handler:       _ControllerRegistryService_StreamSnapshots_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "merionyx/gateway/controller_registry/v1/controller_registry.proto",
}
