// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/proto/v1/auth.proto

package authv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_SyncAccess_FullMethodName      = "/api.auth.v1.AuthService/SyncAccess"
	AuthService_GetAccessConfig_FullMethodName = "/api.auth.v1.AuthService/GetAccessConfig"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService сервис для синхронизации прав доступа
type AuthServiceClient interface {
	// Bidirectional streaming для синхронизации
	SyncAccess(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SyncAccessRequest, SyncAccessResponse], error)
	// Получить текущую конфигурацию (unary)
	GetAccessConfig(ctx context.Context, in *GetAccessConfigRequest, opts ...grpc.CallOption) (*AccessConfig, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) SyncAccess(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SyncAccessRequest, SyncAccessResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuthService_ServiceDesc.Streams[0], AuthService_SyncAccess_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncAccessRequest, SyncAccessResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthService_SyncAccessClient = grpc.BidiStreamingClient[SyncAccessRequest, SyncAccessResponse]

func (c *authServiceClient) GetAccessConfig(ctx context.Context, in *GetAccessConfigRequest, opts ...grpc.CallOption) (*AccessConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessConfig)
	err := c.cc.Invoke(ctx, AuthService_GetAccessConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService сервис для синхронизации прав доступа
type AuthServiceServer interface {
	// Bidirectional streaming для синхронизации
	SyncAccess(grpc.BidiStreamingServer[SyncAccessRequest, SyncAccessResponse]) error
	// Получить текущую конфигурацию (unary)
	GetAccessConfig(context.Context, *GetAccessConfigRequest) (*AccessConfig, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) SyncAccess(grpc.BidiStreamingServer[SyncAccessRequest, SyncAccessResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SyncAccess not implemented")
}
func (UnimplementedAuthServiceServer) GetAccessConfig(context.Context, *GetAccessConfigRequest) (*AccessConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessConfig not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_SyncAccess_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AuthServiceServer).SyncAccess(&grpc.GenericServerStream[SyncAccessRequest, SyncAccessResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthService_SyncAccessServer = grpc.BidiStreamingServer[SyncAccessRequest, SyncAccessResponse]

func _AuthService_GetAccessConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetAccessConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetAccessConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetAccessConfig(ctx, req.(*GetAccessConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.auth.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccessConfig",
			Handler:    _AuthService_GetAccessConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncAccess",
			Handler:       _AuthService_SyncAccess_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/v1/auth.proto",
}
