// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/v1/snapshots.proto

package snapshotsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpdateSnapshotRequest request for updating snapshot
type UpdateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   string                 `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSnapshotRequest) Reset() {
	*x = UpdateSnapshotRequest{}
	mi := &file_api_proto_v1_snapshots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSnapshotRequest) ProtoMessage() {}

func (x *UpdateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_snapshots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*UpdateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_snapshots_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateSnapshotRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

// UpdateSnapshotResponse response for updating snapshot
type UpdateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSnapshotResponse) Reset() {
	*x = UpdateSnapshotResponse{}
	mi := &file_api_proto_v1_snapshots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSnapshotResponse) ProtoMessage() {}

func (x *UpdateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_snapshots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*UpdateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_snapshots_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_v1_snapshots_proto protoreflect.FileDescriptor

const file_api_proto_v1_snapshots_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/v1/snapshots.proto\x12\x10api.snapshots.v1\"9\n" +
	"\x15UpdateSnapshotRequest\x12 \n" +
	"\venvironment\x18\x01 \x01(\tR\venvironment\"2\n" +
	"\x16UpdateSnapshotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2w\n" +
	"\x10SnapshotsService\x12c\n" +
	"\x0eUpdateSnapshot\x12'.api.snapshots.v1.UpdateSnapshotRequest\x1a(.api.snapshots.v1.UpdateSnapshotResponseBEZCmerionyx/api-gateway/control-plane/pkg/api/snapshots/v1;snapshotsv1b\x06proto3"

var (
	file_api_proto_v1_snapshots_proto_rawDescOnce sync.Once
	file_api_proto_v1_snapshots_proto_rawDescData []byte
)

func file_api_proto_v1_snapshots_proto_rawDescGZIP() []byte {
	file_api_proto_v1_snapshots_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_snapshots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_snapshots_proto_rawDesc), len(file_api_proto_v1_snapshots_proto_rawDesc)))
	})
	return file_api_proto_v1_snapshots_proto_rawDescData
}

var file_api_proto_v1_snapshots_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_snapshots_proto_goTypes = []any{
	(*UpdateSnapshotRequest)(nil),  // 0: api.snapshots.v1.UpdateSnapshotRequest
	(*UpdateSnapshotResponse)(nil), // 1: api.snapshots.v1.UpdateSnapshotResponse
}
var file_api_proto_v1_snapshots_proto_depIdxs = []int32{
	0, // 0: api.snapshots.v1.SnapshotsService.UpdateSnapshot:input_type -> api.snapshots.v1.UpdateSnapshotRequest
	1, // 1: api.snapshots.v1.SnapshotsService.UpdateSnapshot:output_type -> api.snapshots.v1.UpdateSnapshotResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_snapshots_proto_init() }
func file_api_proto_v1_snapshots_proto_init() {
	if File_api_proto_v1_snapshots_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_snapshots_proto_rawDesc), len(file_api_proto_v1_snapshots_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_snapshots_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_snapshots_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_snapshots_proto_msgTypes,
	}.Build()
	File_api_proto_v1_snapshots_proto = out.File
	file_api_proto_v1_snapshots_proto_goTypes = nil
	file_api_proto_v1_snapshots_proto_depIdxs = nil
}
