FROM golang:1.25.1-alpine

RUN apk add --no-cache git ca-certificates tzdata curl

# Install Air
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /usr/local/bin

WORKDIR /app

# Копируем только go.mod и go.sum для кэширования зависимостей
COPY go.mod go.sum ./

RUN go mod download

# Теперь копируем остальные исходники
COPY . .

EXPOSE 8080 8443 8444

CMD ["air", "-c", ".air.toml"]