
FROM golang:1.25.1-alpine

RUN apk add --no-cache git ca-certificates tzdata curl

# Install Air
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /usr/local/bin

WORKDIR /app

# Copy go.mod and go.sum for caching dependencies
COPY go.mod go.sum ./

RUN go mod download

# Now copy the rest of the sources
COPY . .

EXPOSE 8080 8443 8444

CMD ["air", "-c", ".air.auth-sidecar.toml"]