// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/v1/environment.proto

package environmentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Environment message for environment
type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{0}
}

func (x *Environment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Environment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Environment) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Environment) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Environment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Environment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateEnvironmentRequest request for creating environment
type CreateEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvironmentRequest) Reset() {
	*x = CreateEnvironmentRequest{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvironmentRequest) ProtoMessage() {}

func (x *CreateEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*CreateEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEnvironmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEnvironmentRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateEnvironmentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// CreateEnvironmentResponse response for creating environment
type CreateEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   *Environment           `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvironmentResponse) Reset() {
	*x = CreateEnvironmentResponse{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvironmentResponse) ProtoMessage() {}

func (x *CreateEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*CreateEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEnvironmentResponse) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

// GetEnvironmentRequest request for getting environment
type GetEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentRequest) Reset() {
	*x = GetEnvironmentRequest{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentRequest) ProtoMessage() {}

func (x *GetEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*GetEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{3}
}

func (x *GetEnvironmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetEnvironmentResponse response for getting environment
type GetEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   *Environment           `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentResponse) Reset() {
	*x = GetEnvironmentResponse{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentResponse) ProtoMessage() {}

func (x *GetEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*GetEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{4}
}

func (x *GetEnvironmentResponse) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

// GetEnvironmentByNameRequest request for getting environment by name
type GetEnvironmentByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentByNameRequest) Reset() {
	*x = GetEnvironmentByNameRequest{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentByNameRequest) ProtoMessage() {}

func (x *GetEnvironmentByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentByNameRequest.ProtoReflect.Descriptor instead.
func (*GetEnvironmentByNameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{5}
}

func (x *GetEnvironmentByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetEnvironmentByNameResponse response for getting environment by name
type GetEnvironmentByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   *Environment           `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentByNameResponse) Reset() {
	*x = GetEnvironmentByNameResponse{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentByNameResponse) ProtoMessage() {}

func (x *GetEnvironmentByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentByNameResponse.ProtoReflect.Descriptor instead.
func (*GetEnvironmentByNameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{6}
}

func (x *GetEnvironmentByNameResponse) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

// GetEnvironmentsRequest request for getting list of environments
type GetEnvironmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentsRequest) Reset() {
	*x = GetEnvironmentsRequest{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentsRequest) ProtoMessage() {}

func (x *GetEnvironmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentsRequest.ProtoReflect.Descriptor instead.
func (*GetEnvironmentsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{7}
}

// GetEnvironmentsResponse response for getting list of environments
type GetEnvironmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environments  []*Environment         `protobuf:"bytes,1,rep,name=environments,proto3" json:"environments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentsResponse) Reset() {
	*x = GetEnvironmentsResponse{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentsResponse) ProtoMessage() {}

func (x *GetEnvironmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentsResponse.ProtoReflect.Descriptor instead.
func (*GetEnvironmentsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{8}
}

func (x *GetEnvironmentsResponse) GetEnvironments() []*Environment {
	if x != nil {
		return x.Environments
	}
	return nil
}

// GetEnvironmentsByTenantRequest request for getting environments by tenant
type GetEnvironmentsByTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentsByTenantRequest) Reset() {
	*x = GetEnvironmentsByTenantRequest{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentsByTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentsByTenantRequest) ProtoMessage() {}

func (x *GetEnvironmentsByTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentsByTenantRequest.ProtoReflect.Descriptor instead.
func (*GetEnvironmentsByTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{9}
}

func (x *GetEnvironmentsByTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// GetEnvironmentsByTenantResponse response for getting environments by tenant
type GetEnvironmentsByTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environments  []*Environment         `protobuf:"bytes,1,rep,name=environments,proto3" json:"environments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentsByTenantResponse) Reset() {
	*x = GetEnvironmentsByTenantResponse{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentsByTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentsByTenantResponse) ProtoMessage() {}

func (x *GetEnvironmentsByTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentsByTenantResponse.ProtoReflect.Descriptor instead.
func (*GetEnvironmentsByTenantResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{10}
}

func (x *GetEnvironmentsByTenantResponse) GetEnvironments() []*Environment {
	if x != nil {
		return x.Environments
	}
	return nil
}

// UpdateEnvironmentRequest request for updating environment
type UpdateEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEnvironmentRequest) Reset() {
	*x = UpdateEnvironmentRequest{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnvironmentRequest) ProtoMessage() {}

func (x *UpdateEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateEnvironmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEnvironmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEnvironmentRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

// UpdateEnvironmentResponse response for updating environment
type UpdateEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   *Environment           `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEnvironmentResponse) Reset() {
	*x = UpdateEnvironmentResponse{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnvironmentResponse) ProtoMessage() {}

func (x *UpdateEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateEnvironmentResponse) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

// DeleteEnvironmentRequest request for deleting environment
type DeleteEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEnvironmentRequest) Reset() {
	*x = DeleteEnvironmentRequest{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnvironmentRequest) ProtoMessage() {}

func (x *DeleteEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteEnvironmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteEnvironmentResponse response for deleting environment
type DeleteEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEnvironmentResponse) Reset() {
	*x = DeleteEnvironmentResponse{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnvironmentResponse) ProtoMessage() {}

func (x *DeleteEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{14}
}

// MapEnvironmentToTenantRequest request for mapping environment to tenant
type MapEnvironmentToTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapEnvironmentToTenantRequest) Reset() {
	*x = MapEnvironmentToTenantRequest{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapEnvironmentToTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEnvironmentToTenantRequest) ProtoMessage() {}

func (x *MapEnvironmentToTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapEnvironmentToTenantRequest.ProtoReflect.Descriptor instead.
func (*MapEnvironmentToTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{15}
}

func (x *MapEnvironmentToTenantRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *MapEnvironmentToTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// MapEnvironmentToTenantResponse response for mapping environment to tenant
type MapEnvironmentToTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapEnvironmentToTenantResponse) Reset() {
	*x = MapEnvironmentToTenantResponse{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapEnvironmentToTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEnvironmentToTenantResponse) ProtoMessage() {}

func (x *MapEnvironmentToTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapEnvironmentToTenantResponse.ProtoReflect.Descriptor instead.
func (*MapEnvironmentToTenantResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{16}
}

// UnmapEnvironmentFromTenantRequest request for unmapping environment from tenant
type UnmapEnvironmentFromTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmapEnvironmentFromTenantRequest) Reset() {
	*x = UnmapEnvironmentFromTenantRequest{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmapEnvironmentFromTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmapEnvironmentFromTenantRequest) ProtoMessage() {}

func (x *UnmapEnvironmentFromTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmapEnvironmentFromTenantRequest.ProtoReflect.Descriptor instead.
func (*UnmapEnvironmentFromTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{17}
}

func (x *UnmapEnvironmentFromTenantRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *UnmapEnvironmentFromTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// UnmapEnvironmentFromTenantResponse response for unmapping environment from tenant
type UnmapEnvironmentFromTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmapEnvironmentFromTenantResponse) Reset() {
	*x = UnmapEnvironmentFromTenantResponse{}
	mi := &file_api_proto_v1_environment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmapEnvironmentFromTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmapEnvironmentFromTenantResponse) ProtoMessage() {}

func (x *UnmapEnvironmentFromTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_environment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmapEnvironmentFromTenantResponse.ProtoReflect.Descriptor instead.
func (*UnmapEnvironmentFromTenantResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_environment_proto_rawDescGZIP(), []int{18}
}

var File_api_proto_v1_environment_proto protoreflect.FileDescriptor

const file_api_proto_v1_environment_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/v1/environment.proto\x12\x12api.environment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf5\x01\n" +
	"\vEnvironment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"|\n" +
	"\x18CreateEnvironmentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"^\n" +
	"\x19CreateEnvironmentResponse\x12A\n" +
	"\venvironment\x18\x01 \x01(\v2\x1f.api.environment.v1.EnvironmentR\venvironment\"'\n" +
	"\x15GetEnvironmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"[\n" +
	"\x16GetEnvironmentResponse\x12A\n" +
	"\venvironment\x18\x01 \x01(\v2\x1f.api.environment.v1.EnvironmentR\venvironment\"1\n" +
	"\x1bGetEnvironmentByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"a\n" +
	"\x1cGetEnvironmentByNameResponse\x12A\n" +
	"\venvironment\x18\x01 \x01(\v2\x1f.api.environment.v1.EnvironmentR\venvironment\"\x18\n" +
	"\x16GetEnvironmentsRequest\"^\n" +
	"\x17GetEnvironmentsResponse\x12C\n" +
	"\fenvironments\x18\x01 \x03(\v2\x1f.api.environment.v1.EnvironmentR\fenvironments\"=\n" +
	"\x1eGetEnvironmentsByTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"f\n" +
	"\x1fGetEnvironmentsByTenantResponse\x12C\n" +
	"\fenvironments\x18\x01 \x03(\v2\x1f.api.environment.v1.EnvironmentR\fenvironments\"o\n" +
	"\x18UpdateEnvironmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\"^\n" +
	"\x19UpdateEnvironmentResponse\x12A\n" +
	"\venvironment\x18\x01 \x01(\v2\x1f.api.environment.v1.EnvironmentR\venvironment\"*\n" +
	"\x18DeleteEnvironmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19DeleteEnvironmentResponse\"c\n" +
	"\x1dMapEnvironmentToTenantRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\" \n" +
	"\x1eMapEnvironmentToTenantResponse\"g\n" +
	"!UnmapEnvironmentFromTenantRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"$\n" +
	"\"UnmapEnvironmentFromTenantResponse2\xce\b\n" +
	"\x12EnvironmentService\x12p\n" +
	"\x11CreateEnvironment\x12,.api.environment.v1.CreateEnvironmentRequest\x1a-.api.environment.v1.CreateEnvironmentResponse\x12g\n" +
	"\x0eGetEnvironment\x12).api.environment.v1.GetEnvironmentRequest\x1a*.api.environment.v1.GetEnvironmentResponse\x12y\n" +
	"\x14GetEnvironmentByName\x12/.api.environment.v1.GetEnvironmentByNameRequest\x1a0.api.environment.v1.GetEnvironmentByNameResponse\x12j\n" +
	"\x0fGetEnvironments\x12*.api.environment.v1.GetEnvironmentsRequest\x1a+.api.environment.v1.GetEnvironmentsResponse\x12\x82\x01\n" +
	"\x17GetEnvironmentsByTenant\x122.api.environment.v1.GetEnvironmentsByTenantRequest\x1a3.api.environment.v1.GetEnvironmentsByTenantResponse\x12p\n" +
	"\x11UpdateEnvironment\x12,.api.environment.v1.UpdateEnvironmentRequest\x1a-.api.environment.v1.UpdateEnvironmentResponse\x12p\n" +
	"\x11DeleteEnvironment\x12,.api.environment.v1.DeleteEnvironmentRequest\x1a-.api.environment.v1.DeleteEnvironmentResponse\x12\x7f\n" +
	"\x16MapEnvironmentToTenant\x121.api.environment.v1.MapEnvironmentToTenantRequest\x1a2.api.environment.v1.MapEnvironmentToTenantResponse\x12\x8b\x01\n" +
	"\x1aUnmapEnvironmentFromTenant\x125.api.environment.v1.UnmapEnvironmentFromTenantRequest\x1a6.api.environment.v1.UnmapEnvironmentFromTenantResponseBIZGmerionyx/api-gateway/control-plane/pkg/api/environment/v1;environmentv1b\x06proto3"

var (
	file_api_proto_v1_environment_proto_rawDescOnce sync.Once
	file_api_proto_v1_environment_proto_rawDescData []byte
)

func file_api_proto_v1_environment_proto_rawDescGZIP() []byte {
	file_api_proto_v1_environment_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_environment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_environment_proto_rawDesc), len(file_api_proto_v1_environment_proto_rawDesc)))
	})
	return file_api_proto_v1_environment_proto_rawDescData
}

var file_api_proto_v1_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_proto_v1_environment_proto_goTypes = []any{
	(*Environment)(nil),                        // 0: api.environment.v1.Environment
	(*CreateEnvironmentRequest)(nil),           // 1: api.environment.v1.CreateEnvironmentRequest
	(*CreateEnvironmentResponse)(nil),          // 2: api.environment.v1.CreateEnvironmentResponse
	(*GetEnvironmentRequest)(nil),              // 3: api.environment.v1.GetEnvironmentRequest
	(*GetEnvironmentResponse)(nil),             // 4: api.environment.v1.GetEnvironmentResponse
	(*GetEnvironmentByNameRequest)(nil),        // 5: api.environment.v1.GetEnvironmentByNameRequest
	(*GetEnvironmentByNameResponse)(nil),       // 6: api.environment.v1.GetEnvironmentByNameResponse
	(*GetEnvironmentsRequest)(nil),             // 7: api.environment.v1.GetEnvironmentsRequest
	(*GetEnvironmentsResponse)(nil),            // 8: api.environment.v1.GetEnvironmentsResponse
	(*GetEnvironmentsByTenantRequest)(nil),     // 9: api.environment.v1.GetEnvironmentsByTenantRequest
	(*GetEnvironmentsByTenantResponse)(nil),    // 10: api.environment.v1.GetEnvironmentsByTenantResponse
	(*UpdateEnvironmentRequest)(nil),           // 11: api.environment.v1.UpdateEnvironmentRequest
	(*UpdateEnvironmentResponse)(nil),          // 12: api.environment.v1.UpdateEnvironmentResponse
	(*DeleteEnvironmentRequest)(nil),           // 13: api.environment.v1.DeleteEnvironmentRequest
	(*DeleteEnvironmentResponse)(nil),          // 14: api.environment.v1.DeleteEnvironmentResponse
	(*MapEnvironmentToTenantRequest)(nil),      // 15: api.environment.v1.MapEnvironmentToTenantRequest
	(*MapEnvironmentToTenantResponse)(nil),     // 16: api.environment.v1.MapEnvironmentToTenantResponse
	(*UnmapEnvironmentFromTenantRequest)(nil),  // 17: api.environment.v1.UnmapEnvironmentFromTenantRequest
	(*UnmapEnvironmentFromTenantResponse)(nil), // 18: api.environment.v1.UnmapEnvironmentFromTenantResponse
	(*structpb.Struct)(nil),                    // 19: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),              // 20: google.protobuf.Timestamp
}
var file_api_proto_v1_environment_proto_depIdxs = []int32{
	19, // 0: api.environment.v1.Environment.config:type_name -> google.protobuf.Struct
	20, // 1: api.environment.v1.Environment.created_at:type_name -> google.protobuf.Timestamp
	20, // 2: api.environment.v1.Environment.updated_at:type_name -> google.protobuf.Timestamp
	19, // 3: api.environment.v1.CreateEnvironmentRequest.config:type_name -> google.protobuf.Struct
	0,  // 4: api.environment.v1.CreateEnvironmentResponse.environment:type_name -> api.environment.v1.Environment
	0,  // 5: api.environment.v1.GetEnvironmentResponse.environment:type_name -> api.environment.v1.Environment
	0,  // 6: api.environment.v1.GetEnvironmentByNameResponse.environment:type_name -> api.environment.v1.Environment
	0,  // 7: api.environment.v1.GetEnvironmentsResponse.environments:type_name -> api.environment.v1.Environment
	0,  // 8: api.environment.v1.GetEnvironmentsByTenantResponse.environments:type_name -> api.environment.v1.Environment
	19, // 9: api.environment.v1.UpdateEnvironmentRequest.config:type_name -> google.protobuf.Struct
	0,  // 10: api.environment.v1.UpdateEnvironmentResponse.environment:type_name -> api.environment.v1.Environment
	1,  // 11: api.environment.v1.EnvironmentService.CreateEnvironment:input_type -> api.environment.v1.CreateEnvironmentRequest
	3,  // 12: api.environment.v1.EnvironmentService.GetEnvironment:input_type -> api.environment.v1.GetEnvironmentRequest
	5,  // 13: api.environment.v1.EnvironmentService.GetEnvironmentByName:input_type -> api.environment.v1.GetEnvironmentByNameRequest
	7,  // 14: api.environment.v1.EnvironmentService.GetEnvironments:input_type -> api.environment.v1.GetEnvironmentsRequest
	9,  // 15: api.environment.v1.EnvironmentService.GetEnvironmentsByTenant:input_type -> api.environment.v1.GetEnvironmentsByTenantRequest
	11, // 16: api.environment.v1.EnvironmentService.UpdateEnvironment:input_type -> api.environment.v1.UpdateEnvironmentRequest
	13, // 17: api.environment.v1.EnvironmentService.DeleteEnvironment:input_type -> api.environment.v1.DeleteEnvironmentRequest
	15, // 18: api.environment.v1.EnvironmentService.MapEnvironmentToTenant:input_type -> api.environment.v1.MapEnvironmentToTenantRequest
	17, // 19: api.environment.v1.EnvironmentService.UnmapEnvironmentFromTenant:input_type -> api.environment.v1.UnmapEnvironmentFromTenantRequest
	2,  // 20: api.environment.v1.EnvironmentService.CreateEnvironment:output_type -> api.environment.v1.CreateEnvironmentResponse
	4,  // 21: api.environment.v1.EnvironmentService.GetEnvironment:output_type -> api.environment.v1.GetEnvironmentResponse
	6,  // 22: api.environment.v1.EnvironmentService.GetEnvironmentByName:output_type -> api.environment.v1.GetEnvironmentByNameResponse
	8,  // 23: api.environment.v1.EnvironmentService.GetEnvironments:output_type -> api.environment.v1.GetEnvironmentsResponse
	10, // 24: api.environment.v1.EnvironmentService.GetEnvironmentsByTenant:output_type -> api.environment.v1.GetEnvironmentsByTenantResponse
	12, // 25: api.environment.v1.EnvironmentService.UpdateEnvironment:output_type -> api.environment.v1.UpdateEnvironmentResponse
	14, // 26: api.environment.v1.EnvironmentService.DeleteEnvironment:output_type -> api.environment.v1.DeleteEnvironmentResponse
	16, // 27: api.environment.v1.EnvironmentService.MapEnvironmentToTenant:output_type -> api.environment.v1.MapEnvironmentToTenantResponse
	18, // 28: api.environment.v1.EnvironmentService.UnmapEnvironmentFromTenant:output_type -> api.environment.v1.UnmapEnvironmentFromTenantResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_v1_environment_proto_init() }
func file_api_proto_v1_environment_proto_init() {
	if File_api_proto_v1_environment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_environment_proto_rawDesc), len(file_api_proto_v1_environment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_environment_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_environment_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_environment_proto_msgTypes,
	}.Build()
	File_api_proto_v1_environment_proto = out.File
	file_api_proto_v1_environment_proto_goTypes = nil
	file_api_proto_v1_environment_proto_depIdxs = nil
}
