apiVersion: v2
name: api-gateway-control-plane
description: API Gateway control plane (Controller, API Server, Contract Syncer)
type: application
version: latest
appVersion: latest
icon: https://avatars.githubusercontent.com/u/208366109?s=512
