server:
  http1_port: "8080"
  http2_port: "8443"
  grpc_port: "8090"
  host: "localhost"

repositories:
- name: api-gateway-schemas-https
  source: git
  url: "https://github.com/MikhailMinaev/api-gateway-schemas.git"
  auth:
    type: "token"
    token_env: "GITHUB_ACCESS_TOKEN"
    # - name: api-gateway-schemas-ssh
    #   url: "git@github.com:MikhailMinaev/api-gateway-schemas.git"
    #   auth:
    #     type: "ssh"
    #     ssh_key_path: "./secrets/keys/api-schemas-ed25519"
    # ssh_key_env: "SSH_PRIVATE_KEY"

services:
- name: be-service-01
  url: "http://localhost:8080"
- name: be-service-02
  url: "http://localhost:8081"

environments:
- name: dev
  contracts:
    name: api-gateway-schemas
    repository: api-gateway-schemas-https
    ref: main
