server:
  http1_port: "8080"
  http2_port: "8443"
  grpc_port: "8090"
  host: "localhost"

database:
  type: "postgresql"
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "postgres"
  options:
    ssl_mode: "disable"
    max_open_conns: 25
    max_idle_conns: 5
    migrations_path: "./databases/postgres/migrations"
