// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: listeners.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createListener = `-- name: CreateListener :exec
INSERT INTO control_plane.listeners (uuid, name, config)
VALUES ($1, $2, $3)
`

type CreateListenerParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	Name   string    `json:"name"`
	Config []byte    `json:"config"`
}

func (q *Queries) CreateListener(ctx context.Context, arg CreateListenerParams) error {
	_, err := q.db.Exec(ctx, createListener, arg.Uuid, arg.Name, arg.Config)
	return err
}

const deleteListener = `-- name: DeleteListener :exec
DELETE FROM control_plane.listeners WHERE uuid = $1
`

func (q *Queries) DeleteListener(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteListener, argUuid)
	return err
}

const getListenerByUUID = `-- name: GetListenerByUUID :one
SELECT uuid, name, config FROM control_plane.listeners WHERE uuid = $1
`

func (q *Queries) GetListenerByUUID(ctx context.Context, argUuid uuid.UUID) (ControlPlaneListener, error) {
	row := q.db.QueryRow(ctx, getListenerByUUID, argUuid)
	var i ControlPlaneListener
	err := row.Scan(&i.Uuid, &i.Name, &i.Config)
	return i, err
}

const getListeners = `-- name: GetListeners :many
SELECT uuid, name, config FROM control_plane.listeners
`

func (q *Queries) GetListeners(ctx context.Context) ([]ControlPlaneListener, error) {
	rows, err := q.db.Query(ctx, getListeners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlPlaneListener
	for rows.Next() {
		var i ControlPlaneListener
		if err := rows.Scan(&i.Uuid, &i.Name, &i.Config); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListenersByEnvironmentUUID = `-- name: GetListenersByEnvironmentUUID :many
SELECT l.uuid, l.name, l.config FROM control_plane.listeners l
INNER JOIN control_plane.listeners_environments le ON l.uuid = le.listener_uuid
WHERE le.environment_uuid = $1
`

func (q *Queries) GetListenersByEnvironmentUUID(ctx context.Context, environmentUuid uuid.UUID) ([]ControlPlaneListener, error) {
	rows, err := q.db.Query(ctx, getListenersByEnvironmentUUID, environmentUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlPlaneListener
	for rows.Next() {
		var i ControlPlaneListener
		if err := rows.Scan(&i.Uuid, &i.Name, &i.Config); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateListener = `-- name: UpdateListener :exec
UPDATE control_plane.listeners SET name = $2, config = $3 WHERE uuid = $1
`

type UpdateListenerParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	Name   string    `json:"name"`
	Config []byte    `json:"config"`
}

func (q *Queries) UpdateListener(ctx context.Context, arg UpdateListenerParams) error {
	_, err := q.db.Exec(ctx, updateListener, arg.Uuid, arg.Name, arg.Config)
	return err
}
