networks:
    default:

services:
    gateway-controller-dev:
        container_name: merionyx-api-gateway-controller-dev
        build:
            context: ../../..
            dockerfile: Dockerfile.controller.dev
        command: air -c .air.controller.toml
        environment:
            - CONFIG_PATH=./configs/controller/config.dev.yaml
            - SSH_KNOWN_HOSTS=/app/secrets/known_hosts
        env_file:
            - ../../../secrets/.env
        ports:
            - 10080:8080
            - 10443:8443
            - 19090:19090
            - 19091:19091
        develop:
          watch:
            - path: ../../internal/controller
              target: /app/internal/controller
              action: sync
            - path: ../../internal/shared
              target: /app/internal/shared
              action: sync
            - path: ../../cmd/controller
              target: /app/cmd/controller
              action: sync
            - path: ../../configs/controller
              target: /app/configs/controller
              action: sync
            - path: ../../pkg
              target: /app/pkg
              action: sync
        networks:
            - default
        depends_on:
            - etcd-controller-dev
    gateway-controller-prod:
        container_name: merionyx-api-gateway-controller-prod
        build:
            context: ../../..
            dockerfile: Dockerfile.controller.dev
        command: air -c .air.controller.toml
        environment:
            - CONFIG_PATH=./configs/controller/config.prod.yaml
            - SSH_KNOWN_HOSTS=/app/secrets/known_hosts
        env_file:
            - ../../../secrets/.env
        ports:
            - 11080:8080
            - 11443:8443
            - 19190:19090
            - 19191:19091
        develop:
          watch:
            - path: ../../internal/controller
              target: /app/internal/controller
              action: sync
            - path: ../../internal/shared
              target: /app/internal/shared
              action: sync
            - path: ../../cmd/controller
              target: /app/cmd/controller
              action: sync
            - path: ../../configs/controller
              target: /app/configs/controller
              action: sync
            - path: ../../pkg
              target: /app/pkg
              action: sync
        networks:
            - default
        depends_on:
            - etcd-controller-prod
    gateway-api-server:
        container_name: merionyx-api-gateway-api-server
        build:
            context: ../../..
            dockerfile: Dockerfile.api-server.dev
        command: air -c .air.api-server.toml
        environment:
            - CONFIG_PATH=./configs/api-server/config.yaml
            - SSH_KNOWN_HOSTS=/app/secrets/known_hosts
        env_file:
            - ../../../secrets/.env
        ports:
            - 12080:8080
            - 12443:8443
            - 19093:19093
        develop:
          watch:
            - path: ../../internal/api-server
              target: /app/internal/api-server
              action: sync
            - path: ../../internal/shared
              target: /app/internal/shared
              action: sync
            - path: ../../cmd/api-server
              target: /app/cmd/api-server
              action: sync
            - path: ../../configs/api-server
              target: /app/configs/api-server
              action: sync
            - path: ../../pkg
              target: /app/pkg
              action: sync
        networks:
            - default
        depends_on:
            - etcd-api-server
    gateway-contract-syncer:
        container_name: merionyx-api-gateway-contract-syncer
        build:
            context: ../../..
            dockerfile: Dockerfile.contract-syncer.dev
        command: air -c .air.contract-syncer.toml
        environment:
            - CONFIG_PATH=./configs/contract-syncer/config.yaml
            - SSH_KNOWN_HOSTS=/app/secrets/known_hosts
        env_file:
            - ../../../secrets/.env
        ports:
            - 19092:19092
        develop:
          watch:
            - path: ../../internal/contract-syncer
              target: /app/internal/contract-syncer
              action: sync
            - path: ../../internal/shared
              target: /app/internal/shared
              action: sync
            - path: ../../cmd/contract-syncer
              target: /app/cmd/contract-syncer
              action: sync
            - path: ../../configs/api-server
              target: /app/configs/contract-syncer
              action: sync
            - path: ../../pkg
              target: /app/pkg
              action: sync
        networks:
            - default
        depends_on:
            - etcd-api-server
        volumes:
          - ../../../api-gateway-schemas-local:/app/local-dir
