networks:
    default:

services:
    gateway-controller-dev:
        container_name: merionyx-api-gateway-controller-dev
        build:
            context: ../../..
            dockerfile: build/release/Dockerfile.controller
        environment:
            - CONFIG_PATH=./configs/controller/config.dev.yaml
            - SSH_KNOWN_HOSTS=/app/secrets/known_hosts
        env_file:
            - ../../../secrets/.env
        ports:
            - 10080:8080
            - 10443:8443
            - 19090:19090
            - 19091:19091
        networks:
            - default
        depends_on:
            - etcd-controller-dev-1
            - etcd-controller-dev-2
            - etcd-controller-dev-3
    gateway-controller-prod:
        container_name: merionyx-api-gateway-controller-prod
        build:
            context: ../../..
            dockerfile: build/release/Dockerfile.controller
        environment:
            - CONFIG_PATH=./configs/controller/config.prod.yaml
            - SSH_KNOWN_HOSTS=/app/secrets/known_hosts
        env_file:
            - ../../../secrets/.env
        ports:
            - 11080:8080
            - 11443:8443
            - 19190:19090
            - 19191:19091
        networks:
            - default
        depends_on:
            - etcd-controller-prod-1
            - etcd-controller-prod-2
            - etcd-controller-prod-3
    gateway-api-server:
        container_name: merionyx-api-gateway-api-server
        build:
            context: ../../..
            dockerfile: build/release/Dockerfile.api-server
        environment:
            - CONFIG_PATH=./configs/api-server/config.yaml
            - SSH_KNOWN_HOSTS=/app/secrets/known_hosts
        env_file:
            - ../../../secrets/.env
        ports:
            - 12080:8080
            - 12443:8443
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8080/.well-known/jwks.json"]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 40s
        networks:
            - default
        depends_on:
            - etcd-api-server-1
            - etcd-api-server-2
            - etcd-api-server-3
    gateway-contract-syncer:
        container_name: merionyx-api-gateway-contract-syncer
        build:
            context: ../../..
            dockerfile: build/release/Dockerfile.contract-syncer
        environment:
            - CONFIG_PATH=./configs/contract-syncer/config.yaml
            - SSH_KNOWN_HOSTS=/app/secrets/known_hosts
        env_file:
            - ../../../secrets/.env
        ports:
            - 19092:19092
        networks:
            - default
        depends_on:
            - etcd-api-server-1
            - etcd-api-server-2
            - etcd-api-server-3
        volumes:
          - ../../../../api-gateway-schemas-local:/app/local-dir
