networks:
  default:
  dev-network:
    external: true
  prod-network:
    external: true

services:
  sidecar-dev:
    build:
      context: ../../..
      dockerfile: build/dev/Dockerfile.sidecar
    container_name: sidecar-dev
    develop:
      watch:
        - path: ../../internal/sidecar
          target: /app/internal/sidecar
          action: sync
        - path: ../../internal/shared
          target: /app/internal/shared
          action: sync
        - path: ../../cmd/sidecar
          target: /app/cmd/sidecar
          action: sync
        - path: ../../configs/sidecar
          target: /app/configs/sidecar
          action: sync
        - path: ../../pkg
          target: /app/pkg
          action: sync
    ports:
      - "9101:9001"
    environment:
      - CONFIG_PATH=./configs/sidecar/config.dev.yaml
      - SIDECAR_CONTROLLER_ADDRESS=gateway-controller-dev:19090
      - SIDECAR_CONTROLLER_ENVIRONMENT=dev
      - SIDECAR_JWT_JWKS_URL=http://api-server:8080/.well-known/jwks.json
    networks:
      default:
      dev-network:
        aliases:
          - sidecar
    depends_on:
      - gateway-controller-dev
      - gateway-api-server
    restart: unless-stopped
  sidecar-prod:
    build:
      context: ../../..
      dockerfile: build/dev/Dockerfile.sidecar
    container_name: sidecar-prod
    develop:
      watch:
        - path: ../../internal/sidecar
          target: /app/internal/sidecar
          action: sync
        - path: ../../internal/shared
          target: /app/internal/shared
          action: sync
        - path: ../../cmd/sidecar
          target: /app/cmd/sidecar
          action: sync
        - path: ../../configs/sidecar
          target: /app/configs/sidecar
          action: sync
        - path: ../../pkg
          target: /app/pkg
          action: sync
    ports:
      - "9102:9001"
    environment:
      - CONFIG_PATH=./configs/sidecar/config.prod.yaml
      - SIDECAR_CONTROLLER_ADDRESS=gateway-controller-prod:19090
      - SIDECAR_CONTROLLER_ENVIRONMENT=dev
      - SIDECAR_JWT_JWKS_URL=http://api-server:8080/.well-known/jwks.json
    networks:
      default:
      prod-network:
        aliases:
          - sidecar
    depends_on:
      - gateway-controller-prod
      - gateway-api-server
    restart: unless-stopped
