apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agwedge.fullname" . }}-auth
  labels:
    {{- include "agwedge.labels" . | nindent 4 }}
data:
  sidecar.yaml: |
{{ include "agwedge.auth.config.merged" . | nindent 4 }}
