apiVersion: v2
name: edge
description: API Gateway edge (Envoy + Auth Sidecar)
type: application
version: 0.0.0
appVersion: latest
icon: https://avatars.githubusercontent.com/u/208366109?s=512
sources:
- https://github.com/merionyx/api-gateway
