apiVersion: v2
name: api-gateway-edge
description: Merionyx API Gateway edge (Envoy + Sidecar)
type: application
version: 0.0.0
appVersion: latest
icon: https://avatars.githubusercontent.com/u/208366109?s=512
sources:
- https://github.com/merionyx/api-gateway
