// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/v1/listener.proto

package listenerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Listener message for listener
type Listener struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,4,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listener) Reset() {
	*x = Listener{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listener) ProtoMessage() {}

func (x *Listener) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listener.ProtoReflect.Descriptor instead.
func (*Listener) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{0}
}

func (x *Listener) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Listener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listener) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Listener) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *Listener) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Listener) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateListenerRequest request for creating listener
type CreateListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,3,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListenerRequest) Reset() {
	*x = CreateListenerRequest{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListenerRequest) ProtoMessage() {}

func (x *CreateListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListenerRequest.ProtoReflect.Descriptor instead.
func (*CreateListenerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{1}
}

func (x *CreateListenerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateListenerRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateListenerRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

// CreateListenerResponse response for creating listener
type CreateListenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listener      *Listener              `protobuf:"bytes,1,opt,name=listener,proto3" json:"listener,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListenerResponse) Reset() {
	*x = CreateListenerResponse{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListenerResponse) ProtoMessage() {}

func (x *CreateListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListenerResponse.ProtoReflect.Descriptor instead.
func (*CreateListenerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{2}
}

func (x *CreateListenerResponse) GetListener() *Listener {
	if x != nil {
		return x.Listener
	}
	return nil
}

// GetListenerRequest request for getting listener
type GetListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListenerRequest) Reset() {
	*x = GetListenerRequest{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenerRequest) ProtoMessage() {}

func (x *GetListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenerRequest.ProtoReflect.Descriptor instead.
func (*GetListenerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{3}
}

func (x *GetListenerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetListenerResponse response for getting listener
type GetListenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listener      *Listener              `protobuf:"bytes,1,opt,name=listener,proto3" json:"listener,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListenerResponse) Reset() {
	*x = GetListenerResponse{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenerResponse) ProtoMessage() {}

func (x *GetListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenerResponse.ProtoReflect.Descriptor instead.
func (*GetListenerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{4}
}

func (x *GetListenerResponse) GetListener() *Listener {
	if x != nil {
		return x.Listener
	}
	return nil
}

// GetListenerByNameRequest request for getting listener by name
type GetListenerByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListenerByNameRequest) Reset() {
	*x = GetListenerByNameRequest{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenerByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenerByNameRequest) ProtoMessage() {}

func (x *GetListenerByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenerByNameRequest.ProtoReflect.Descriptor instead.
func (*GetListenerByNameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{5}
}

func (x *GetListenerByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetListenerByNameResponse response for getting listener by name
type GetListenerByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listener      *Listener              `protobuf:"bytes,1,opt,name=listener,proto3" json:"listener,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListenerByNameResponse) Reset() {
	*x = GetListenerByNameResponse{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenerByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenerByNameResponse) ProtoMessage() {}

func (x *GetListenerByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenerByNameResponse.ProtoReflect.Descriptor instead.
func (*GetListenerByNameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{6}
}

func (x *GetListenerByNameResponse) GetListener() *Listener {
	if x != nil {
		return x.Listener
	}
	return nil
}

// GetListenersRequest request for getting list of listeners
type GetListenersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListenersRequest) Reset() {
	*x = GetListenersRequest{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenersRequest) ProtoMessage() {}

func (x *GetListenersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenersRequest.ProtoReflect.Descriptor instead.
func (*GetListenersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{7}
}

// GetListenersResponse response for getting list of listeners
type GetListenersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listeners     []*Listener            `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListenersResponse) Reset() {
	*x = GetListenersResponse{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenersResponse) ProtoMessage() {}

func (x *GetListenersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenersResponse.ProtoReflect.Descriptor instead.
func (*GetListenersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{8}
}

func (x *GetListenersResponse) GetListeners() []*Listener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

// GetListenersByEnvironmentRequest request for getting listeners by environment
type GetListenersByEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListenersByEnvironmentRequest) Reset() {
	*x = GetListenersByEnvironmentRequest{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenersByEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenersByEnvironmentRequest) ProtoMessage() {}

func (x *GetListenersByEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenersByEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*GetListenersByEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{9}
}

func (x *GetListenersByEnvironmentRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

// GetListenersByEnvironmentResponse response for getting listeners by environment
type GetListenersByEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listeners     []*Listener            `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListenersByEnvironmentResponse) Reset() {
	*x = GetListenersByEnvironmentResponse{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenersByEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenersByEnvironmentResponse) ProtoMessage() {}

func (x *GetListenersByEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenersByEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*GetListenersByEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{10}
}

func (x *GetListenersByEnvironmentResponse) GetListeners() []*Listener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

// UpdateListenerRequest request for updating listener
type UpdateListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateListenerRequest) Reset() {
	*x = UpdateListenerRequest{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListenerRequest) ProtoMessage() {}

func (x *UpdateListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListenerRequest.ProtoReflect.Descriptor instead.
func (*UpdateListenerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateListenerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateListenerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateListenerRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

// UpdateListenerResponse response for updating listener
type UpdateListenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listener      *Listener              `protobuf:"bytes,1,opt,name=listener,proto3" json:"listener,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateListenerResponse) Reset() {
	*x = UpdateListenerResponse{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateListenerResponse) ProtoMessage() {}

func (x *UpdateListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateListenerResponse.ProtoReflect.Descriptor instead.
func (*UpdateListenerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateListenerResponse) GetListener() *Listener {
	if x != nil {
		return x.Listener
	}
	return nil
}

// DeleteListenerRequest request for deleting listener
type DeleteListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListenerRequest) Reset() {
	*x = DeleteListenerRequest{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListenerRequest) ProtoMessage() {}

func (x *DeleteListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListenerRequest.ProtoReflect.Descriptor instead.
func (*DeleteListenerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteListenerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteListenerResponse response for deleting listener
type DeleteListenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListenerResponse) Reset() {
	*x = DeleteListenerResponse{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListenerResponse) ProtoMessage() {}

func (x *DeleteListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListenerResponse.ProtoReflect.Descriptor instead.
func (*DeleteListenerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{14}
}

// MapListenerToEnvironmentRequest request for mapping listener to environment
type MapListenerToEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenerId    string                 `protobuf:"bytes,1,opt,name=listener_id,json=listenerId,proto3" json:"listener_id,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapListenerToEnvironmentRequest) Reset() {
	*x = MapListenerToEnvironmentRequest{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapListenerToEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapListenerToEnvironmentRequest) ProtoMessage() {}

func (x *MapListenerToEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapListenerToEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*MapListenerToEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{15}
}

func (x *MapListenerToEnvironmentRequest) GetListenerId() string {
	if x != nil {
		return x.ListenerId
	}
	return ""
}

func (x *MapListenerToEnvironmentRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

// MapListenerToEnvironmentResponse response for mapping listener to environment
type MapListenerToEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapListenerToEnvironmentResponse) Reset() {
	*x = MapListenerToEnvironmentResponse{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapListenerToEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapListenerToEnvironmentResponse) ProtoMessage() {}

func (x *MapListenerToEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapListenerToEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*MapListenerToEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{16}
}

// UnmapListenerFromEnvironmentRequest request for unmapping listener from environment
type UnmapListenerFromEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenerId    string                 `protobuf:"bytes,1,opt,name=listener_id,json=listenerId,proto3" json:"listener_id,omitempty"`
	EnvironmentId string                 `protobuf:"bytes,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmapListenerFromEnvironmentRequest) Reset() {
	*x = UnmapListenerFromEnvironmentRequest{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmapListenerFromEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmapListenerFromEnvironmentRequest) ProtoMessage() {}

func (x *UnmapListenerFromEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmapListenerFromEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*UnmapListenerFromEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{17}
}

func (x *UnmapListenerFromEnvironmentRequest) GetListenerId() string {
	if x != nil {
		return x.ListenerId
	}
	return ""
}

func (x *UnmapListenerFromEnvironmentRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

// UnmapListenerFromEnvironmentResponse response for unmapping listener from environment
type UnmapListenerFromEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmapListenerFromEnvironmentResponse) Reset() {
	*x = UnmapListenerFromEnvironmentResponse{}
	mi := &file_api_proto_v1_listener_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmapListenerFromEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmapListenerFromEnvironmentResponse) ProtoMessage() {}

func (x *UnmapListenerFromEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_listener_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmapListenerFromEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*UnmapListenerFromEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_listener_proto_rawDescGZIP(), []int{18}
}

var File_api_proto_v1_listener_proto protoreflect.FileDescriptor

const file_api_proto_v1_listener_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/v1/listener.proto\x12\x0fapi.listener.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xfc\x01\n" +
	"\bListener\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\x12%\n" +
	"\x0eenvironment_id\x18\x04 \x01(\tR\renvironmentId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x83\x01\n" +
	"\x15CreateListenerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06config\x12%\n" +
	"\x0eenvironment_id\x18\x03 \x01(\tR\renvironmentId\"O\n" +
	"\x16CreateListenerResponse\x125\n" +
	"\blistener\x18\x01 \x01(\v2\x19.api.listener.v1.ListenerR\blistener\"$\n" +
	"\x12GetListenerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x13GetListenerResponse\x125\n" +
	"\blistener\x18\x01 \x01(\v2\x19.api.listener.v1.ListenerR\blistener\".\n" +
	"\x18GetListenerByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"R\n" +
	"\x19GetListenerByNameResponse\x125\n" +
	"\blistener\x18\x01 \x01(\v2\x19.api.listener.v1.ListenerR\blistener\"\x15\n" +
	"\x13GetListenersRequest\"O\n" +
	"\x14GetListenersResponse\x127\n" +
	"\tlisteners\x18\x01 \x03(\v2\x19.api.listener.v1.ListenerR\tlisteners\"I\n" +
	" GetListenersByEnvironmentRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\"\\\n" +
	"!GetListenersByEnvironmentResponse\x127\n" +
	"\tlisteners\x18\x01 \x03(\v2\x19.api.listener.v1.ListenerR\tlisteners\"l\n" +
	"\x15UpdateListenerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\"O\n" +
	"\x16UpdateListenerResponse\x125\n" +
	"\blistener\x18\x01 \x01(\v2\x19.api.listener.v1.ListenerR\blistener\"'\n" +
	"\x15DeleteListenerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteListenerResponse\"i\n" +
	"\x1fMapListenerToEnvironmentRequest\x12\x1f\n" +
	"\vlistener_id\x18\x01 \x01(\tR\n" +
	"listenerId\x12%\n" +
	"\x0eenvironment_id\x18\x02 \x01(\tR\renvironmentId\"\"\n" +
	" MapListenerToEnvironmentResponse\"m\n" +
	"#UnmapListenerFromEnvironmentRequest\x12\x1f\n" +
	"\vlistener_id\x18\x01 \x01(\tR\n" +
	"listenerId\x12%\n" +
	"\x0eenvironment_id\x18\x02 \x01(\tR\renvironmentId\"&\n" +
	"$UnmapListenerFromEnvironmentResponse2\xf1\a\n" +
	"\x0fListenerService\x12a\n" +
	"\x0eCreateListener\x12&.api.listener.v1.CreateListenerRequest\x1a'.api.listener.v1.CreateListenerResponse\x12X\n" +
	"\vGetListener\x12#.api.listener.v1.GetListenerRequest\x1a$.api.listener.v1.GetListenerResponse\x12j\n" +
	"\x11GetListenerByName\x12).api.listener.v1.GetListenerByNameRequest\x1a*.api.listener.v1.GetListenerByNameResponse\x12[\n" +
	"\fGetListeners\x12$.api.listener.v1.GetListenersRequest\x1a%.api.listener.v1.GetListenersResponse\x12\x82\x01\n" +
	"\x19GetListenersByEnvironment\x121.api.listener.v1.GetListenersByEnvironmentRequest\x1a2.api.listener.v1.GetListenersByEnvironmentResponse\x12a\n" +
	"\x0eUpdateListener\x12&.api.listener.v1.UpdateListenerRequest\x1a'.api.listener.v1.UpdateListenerResponse\x12a\n" +
	"\x0eDeleteListener\x12&.api.listener.v1.DeleteListenerRequest\x1a'.api.listener.v1.DeleteListenerResponse\x12\x7f\n" +
	"\x18MapListenerToEnvironment\x120.api.listener.v1.MapListenerToEnvironmentRequest\x1a1.api.listener.v1.MapListenerToEnvironmentResponse\x12\x8b\x01\n" +
	"\x1cUnmapListenerFromEnvironment\x124.api.listener.v1.UnmapListenerFromEnvironmentRequest\x1a5.api.listener.v1.UnmapListenerFromEnvironmentResponseBCZAmerionyx/api-gateway/control-plane/pkg/api/listener/v1;listenerv1b\x06proto3"

var (
	file_api_proto_v1_listener_proto_rawDescOnce sync.Once
	file_api_proto_v1_listener_proto_rawDescData []byte
)

func file_api_proto_v1_listener_proto_rawDescGZIP() []byte {
	file_api_proto_v1_listener_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_listener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_listener_proto_rawDesc), len(file_api_proto_v1_listener_proto_rawDesc)))
	})
	return file_api_proto_v1_listener_proto_rawDescData
}

var file_api_proto_v1_listener_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_proto_v1_listener_proto_goTypes = []any{
	(*Listener)(nil),                             // 0: api.listener.v1.Listener
	(*CreateListenerRequest)(nil),                // 1: api.listener.v1.CreateListenerRequest
	(*CreateListenerResponse)(nil),               // 2: api.listener.v1.CreateListenerResponse
	(*GetListenerRequest)(nil),                   // 3: api.listener.v1.GetListenerRequest
	(*GetListenerResponse)(nil),                  // 4: api.listener.v1.GetListenerResponse
	(*GetListenerByNameRequest)(nil),             // 5: api.listener.v1.GetListenerByNameRequest
	(*GetListenerByNameResponse)(nil),            // 6: api.listener.v1.GetListenerByNameResponse
	(*GetListenersRequest)(nil),                  // 7: api.listener.v1.GetListenersRequest
	(*GetListenersResponse)(nil),                 // 8: api.listener.v1.GetListenersResponse
	(*GetListenersByEnvironmentRequest)(nil),     // 9: api.listener.v1.GetListenersByEnvironmentRequest
	(*GetListenersByEnvironmentResponse)(nil),    // 10: api.listener.v1.GetListenersByEnvironmentResponse
	(*UpdateListenerRequest)(nil),                // 11: api.listener.v1.UpdateListenerRequest
	(*UpdateListenerResponse)(nil),               // 12: api.listener.v1.UpdateListenerResponse
	(*DeleteListenerRequest)(nil),                // 13: api.listener.v1.DeleteListenerRequest
	(*DeleteListenerResponse)(nil),               // 14: api.listener.v1.DeleteListenerResponse
	(*MapListenerToEnvironmentRequest)(nil),      // 15: api.listener.v1.MapListenerToEnvironmentRequest
	(*MapListenerToEnvironmentResponse)(nil),     // 16: api.listener.v1.MapListenerToEnvironmentResponse
	(*UnmapListenerFromEnvironmentRequest)(nil),  // 17: api.listener.v1.UnmapListenerFromEnvironmentRequest
	(*UnmapListenerFromEnvironmentResponse)(nil), // 18: api.listener.v1.UnmapListenerFromEnvironmentResponse
	(*structpb.Struct)(nil),                      // 19: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),                // 20: google.protobuf.Timestamp
}
var file_api_proto_v1_listener_proto_depIdxs = []int32{
	19, // 0: api.listener.v1.Listener.config:type_name -> google.protobuf.Struct
	20, // 1: api.listener.v1.Listener.created_at:type_name -> google.protobuf.Timestamp
	20, // 2: api.listener.v1.Listener.updated_at:type_name -> google.protobuf.Timestamp
	19, // 3: api.listener.v1.CreateListenerRequest.config:type_name -> google.protobuf.Struct
	0,  // 4: api.listener.v1.CreateListenerResponse.listener:type_name -> api.listener.v1.Listener
	0,  // 5: api.listener.v1.GetListenerResponse.listener:type_name -> api.listener.v1.Listener
	0,  // 6: api.listener.v1.GetListenerByNameResponse.listener:type_name -> api.listener.v1.Listener
	0,  // 7: api.listener.v1.GetListenersResponse.listeners:type_name -> api.listener.v1.Listener
	0,  // 8: api.listener.v1.GetListenersByEnvironmentResponse.listeners:type_name -> api.listener.v1.Listener
	19, // 9: api.listener.v1.UpdateListenerRequest.config:type_name -> google.protobuf.Struct
	0,  // 10: api.listener.v1.UpdateListenerResponse.listener:type_name -> api.listener.v1.Listener
	1,  // 11: api.listener.v1.ListenerService.CreateListener:input_type -> api.listener.v1.CreateListenerRequest
	3,  // 12: api.listener.v1.ListenerService.GetListener:input_type -> api.listener.v1.GetListenerRequest
	5,  // 13: api.listener.v1.ListenerService.GetListenerByName:input_type -> api.listener.v1.GetListenerByNameRequest
	7,  // 14: api.listener.v1.ListenerService.GetListeners:input_type -> api.listener.v1.GetListenersRequest
	9,  // 15: api.listener.v1.ListenerService.GetListenersByEnvironment:input_type -> api.listener.v1.GetListenersByEnvironmentRequest
	11, // 16: api.listener.v1.ListenerService.UpdateListener:input_type -> api.listener.v1.UpdateListenerRequest
	13, // 17: api.listener.v1.ListenerService.DeleteListener:input_type -> api.listener.v1.DeleteListenerRequest
	15, // 18: api.listener.v1.ListenerService.MapListenerToEnvironment:input_type -> api.listener.v1.MapListenerToEnvironmentRequest
	17, // 19: api.listener.v1.ListenerService.UnmapListenerFromEnvironment:input_type -> api.listener.v1.UnmapListenerFromEnvironmentRequest
	2,  // 20: api.listener.v1.ListenerService.CreateListener:output_type -> api.listener.v1.CreateListenerResponse
	4,  // 21: api.listener.v1.ListenerService.GetListener:output_type -> api.listener.v1.GetListenerResponse
	6,  // 22: api.listener.v1.ListenerService.GetListenerByName:output_type -> api.listener.v1.GetListenerByNameResponse
	8,  // 23: api.listener.v1.ListenerService.GetListeners:output_type -> api.listener.v1.GetListenersResponse
	10, // 24: api.listener.v1.ListenerService.GetListenersByEnvironment:output_type -> api.listener.v1.GetListenersByEnvironmentResponse
	12, // 25: api.listener.v1.ListenerService.UpdateListener:output_type -> api.listener.v1.UpdateListenerResponse
	14, // 26: api.listener.v1.ListenerService.DeleteListener:output_type -> api.listener.v1.DeleteListenerResponse
	16, // 27: api.listener.v1.ListenerService.MapListenerToEnvironment:output_type -> api.listener.v1.MapListenerToEnvironmentResponse
	18, // 28: api.listener.v1.ListenerService.UnmapListenerFromEnvironment:output_type -> api.listener.v1.UnmapListenerFromEnvironmentResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_v1_listener_proto_init() }
func file_api_proto_v1_listener_proto_init() {
	if File_api_proto_v1_listener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_listener_proto_rawDesc), len(file_api_proto_v1_listener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_listener_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_listener_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_listener_proto_msgTypes,
	}.Build()
	File_api_proto_v1_listener_proto = out.File
	file_api_proto_v1_listener_proto_goTypes = nil
	file_api_proto_v1_listener_proto_depIdxs = nil
}
