// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/proto/v1/listener.proto

package listenerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ListenerService_CreateListener_FullMethodName               = "/api.listener.v1.ListenerService/CreateListener"
	ListenerService_GetListener_FullMethodName                  = "/api.listener.v1.ListenerService/GetListener"
	ListenerService_GetListenerByName_FullMethodName            = "/api.listener.v1.ListenerService/GetListenerByName"
	ListenerService_GetListeners_FullMethodName                 = "/api.listener.v1.ListenerService/GetListeners"
	ListenerService_GetListenersByEnvironment_FullMethodName    = "/api.listener.v1.ListenerService/GetListenersByEnvironment"
	ListenerService_UpdateListener_FullMethodName               = "/api.listener.v1.ListenerService/UpdateListener"
	ListenerService_DeleteListener_FullMethodName               = "/api.listener.v1.ListenerService/DeleteListener"
	ListenerService_MapListenerToEnvironment_FullMethodName     = "/api.listener.v1.ListenerService/MapListenerToEnvironment"
	ListenerService_UnmapListenerFromEnvironment_FullMethodName = "/api.listener.v1.ListenerService/UnmapListenerFromEnvironment"
)

// ListenerServiceClient is the client API for ListenerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ListenerService service for working with listeners
type ListenerServiceClient interface {
	// CreateListener creates new listener
	CreateListener(ctx context.Context, in *CreateListenerRequest, opts ...grpc.CallOption) (*CreateListenerResponse, error)
	// GetListener gets listener by ID
	GetListener(ctx context.Context, in *GetListenerRequest, opts ...grpc.CallOption) (*GetListenerResponse, error)
	// GetListenerByName gets listener by name
	GetListenerByName(ctx context.Context, in *GetListenerByNameRequest, opts ...grpc.CallOption) (*GetListenerByNameResponse, error)
	// GetListeners gets list of all listeners
	GetListeners(ctx context.Context, in *GetListenersRequest, opts ...grpc.CallOption) (*GetListenersResponse, error)
	// GetListenersByEnvironment gets listeners by environment
	GetListenersByEnvironment(ctx context.Context, in *GetListenersByEnvironmentRequest, opts ...grpc.CallOption) (*GetListenersByEnvironmentResponse, error)
	// UpdateListener updates listener
	UpdateListener(ctx context.Context, in *UpdateListenerRequest, opts ...grpc.CallOption) (*UpdateListenerResponse, error)
	// DeleteListener deletes listener
	DeleteListener(ctx context.Context, in *DeleteListenerRequest, opts ...grpc.CallOption) (*DeleteListenerResponse, error)
	// MapListenerToEnvironment maps listener to environment
	MapListenerToEnvironment(ctx context.Context, in *MapListenerToEnvironmentRequest, opts ...grpc.CallOption) (*MapListenerToEnvironmentResponse, error)
	// UnmapListenerFromEnvironment unmaps listener from environment
	UnmapListenerFromEnvironment(ctx context.Context, in *UnmapListenerFromEnvironmentRequest, opts ...grpc.CallOption) (*UnmapListenerFromEnvironmentResponse, error)
}

type listenerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewListenerServiceClient(cc grpc.ClientConnInterface) ListenerServiceClient {
	return &listenerServiceClient{cc}
}

func (c *listenerServiceClient) CreateListener(ctx context.Context, in *CreateListenerRequest, opts ...grpc.CallOption) (*CreateListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateListenerResponse)
	err := c.cc.Invoke(ctx, ListenerService_CreateListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerServiceClient) GetListener(ctx context.Context, in *GetListenerRequest, opts ...grpc.CallOption) (*GetListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListenerResponse)
	err := c.cc.Invoke(ctx, ListenerService_GetListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerServiceClient) GetListenerByName(ctx context.Context, in *GetListenerByNameRequest, opts ...grpc.CallOption) (*GetListenerByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListenerByNameResponse)
	err := c.cc.Invoke(ctx, ListenerService_GetListenerByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerServiceClient) GetListeners(ctx context.Context, in *GetListenersRequest, opts ...grpc.CallOption) (*GetListenersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListenersResponse)
	err := c.cc.Invoke(ctx, ListenerService_GetListeners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerServiceClient) GetListenersByEnvironment(ctx context.Context, in *GetListenersByEnvironmentRequest, opts ...grpc.CallOption) (*GetListenersByEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListenersByEnvironmentResponse)
	err := c.cc.Invoke(ctx, ListenerService_GetListenersByEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerServiceClient) UpdateListener(ctx context.Context, in *UpdateListenerRequest, opts ...grpc.CallOption) (*UpdateListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateListenerResponse)
	err := c.cc.Invoke(ctx, ListenerService_UpdateListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerServiceClient) DeleteListener(ctx context.Context, in *DeleteListenerRequest, opts ...grpc.CallOption) (*DeleteListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteListenerResponse)
	err := c.cc.Invoke(ctx, ListenerService_DeleteListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerServiceClient) MapListenerToEnvironment(ctx context.Context, in *MapListenerToEnvironmentRequest, opts ...grpc.CallOption) (*MapListenerToEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapListenerToEnvironmentResponse)
	err := c.cc.Invoke(ctx, ListenerService_MapListenerToEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerServiceClient) UnmapListenerFromEnvironment(ctx context.Context, in *UnmapListenerFromEnvironmentRequest, opts ...grpc.CallOption) (*UnmapListenerFromEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnmapListenerFromEnvironmentResponse)
	err := c.cc.Invoke(ctx, ListenerService_UnmapListenerFromEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListenerServiceServer is the server API for ListenerService service.
// All implementations must embed UnimplementedListenerServiceServer
// for forward compatibility.
//
// ListenerService service for working with listeners
type ListenerServiceServer interface {
	// CreateListener creates new listener
	CreateListener(context.Context, *CreateListenerRequest) (*CreateListenerResponse, error)
	// GetListener gets listener by ID
	GetListener(context.Context, *GetListenerRequest) (*GetListenerResponse, error)
	// GetListenerByName gets listener by name
	GetListenerByName(context.Context, *GetListenerByNameRequest) (*GetListenerByNameResponse, error)
	// GetListeners gets list of all listeners
	GetListeners(context.Context, *GetListenersRequest) (*GetListenersResponse, error)
	// GetListenersByEnvironment gets listeners by environment
	GetListenersByEnvironment(context.Context, *GetListenersByEnvironmentRequest) (*GetListenersByEnvironmentResponse, error)
	// UpdateListener updates listener
	UpdateListener(context.Context, *UpdateListenerRequest) (*UpdateListenerResponse, error)
	// DeleteListener deletes listener
	DeleteListener(context.Context, *DeleteListenerRequest) (*DeleteListenerResponse, error)
	// MapListenerToEnvironment maps listener to environment
	MapListenerToEnvironment(context.Context, *MapListenerToEnvironmentRequest) (*MapListenerToEnvironmentResponse, error)
	// UnmapListenerFromEnvironment unmaps listener from environment
	UnmapListenerFromEnvironment(context.Context, *UnmapListenerFromEnvironmentRequest) (*UnmapListenerFromEnvironmentResponse, error)
	mustEmbedUnimplementedListenerServiceServer()
}

// UnimplementedListenerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedListenerServiceServer struct{}

func (UnimplementedListenerServiceServer) CreateListener(context.Context, *CreateListenerRequest) (*CreateListenerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateListener not implemented")
}
func (UnimplementedListenerServiceServer) GetListener(context.Context, *GetListenerRequest) (*GetListenerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListener not implemented")
}
func (UnimplementedListenerServiceServer) GetListenerByName(context.Context, *GetListenerByNameRequest) (*GetListenerByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListenerByName not implemented")
}
func (UnimplementedListenerServiceServer) GetListeners(context.Context, *GetListenersRequest) (*GetListenersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListeners not implemented")
}
func (UnimplementedListenerServiceServer) GetListenersByEnvironment(context.Context, *GetListenersByEnvironmentRequest) (*GetListenersByEnvironmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListenersByEnvironment not implemented")
}
func (UnimplementedListenerServiceServer) UpdateListener(context.Context, *UpdateListenerRequest) (*UpdateListenerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateListener not implemented")
}
func (UnimplementedListenerServiceServer) DeleteListener(context.Context, *DeleteListenerRequest) (*DeleteListenerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteListener not implemented")
}
func (UnimplementedListenerServiceServer) MapListenerToEnvironment(context.Context, *MapListenerToEnvironmentRequest) (*MapListenerToEnvironmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapListenerToEnvironment not implemented")
}
func (UnimplementedListenerServiceServer) UnmapListenerFromEnvironment(context.Context, *UnmapListenerFromEnvironmentRequest) (*UnmapListenerFromEnvironmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnmapListenerFromEnvironment not implemented")
}
func (UnimplementedListenerServiceServer) mustEmbedUnimplementedListenerServiceServer() {}
func (UnimplementedListenerServiceServer) testEmbeddedByValue()                         {}

// UnsafeListenerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ListenerServiceServer will
// result in compilation errors.
type UnsafeListenerServiceServer interface {
	mustEmbedUnimplementedListenerServiceServer()
}

func RegisterListenerServiceServer(s grpc.ServiceRegistrar, srv ListenerServiceServer) {
	// If the following call pancis, it indicates UnimplementedListenerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ListenerService_ServiceDesc, srv)
}

func _ListenerService_CreateListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).CreateListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_CreateListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).CreateListener(ctx, req.(*CreateListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerService_GetListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).GetListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_GetListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).GetListener(ctx, req.(*GetListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerService_GetListenerByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListenerByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).GetListenerByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_GetListenerByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).GetListenerByName(ctx, req.(*GetListenerByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerService_GetListeners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListenersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).GetListeners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_GetListeners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).GetListeners(ctx, req.(*GetListenersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerService_GetListenersByEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListenersByEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).GetListenersByEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_GetListenersByEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).GetListenersByEnvironment(ctx, req.(*GetListenersByEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerService_UpdateListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).UpdateListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_UpdateListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).UpdateListener(ctx, req.(*UpdateListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerService_DeleteListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).DeleteListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_DeleteListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).DeleteListener(ctx, req.(*DeleteListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerService_MapListenerToEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapListenerToEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).MapListenerToEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_MapListenerToEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).MapListenerToEnvironment(ctx, req.(*MapListenerToEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerService_UnmapListenerFromEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmapListenerFromEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).UnmapListenerFromEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_UnmapListenerFromEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).UnmapListenerFromEnvironment(ctx, req.(*UnmapListenerFromEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ListenerService_ServiceDesc is the grpc.ServiceDesc for ListenerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ListenerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.listener.v1.ListenerService",
	HandlerType: (*ListenerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateListener",
			Handler:    _ListenerService_CreateListener_Handler,
		},
		{
			MethodName: "GetListener",
			Handler:    _ListenerService_GetListener_Handler,
		},
		{
			MethodName: "GetListenerByName",
			Handler:    _ListenerService_GetListenerByName_Handler,
		},
		{
			MethodName: "GetListeners",
			Handler:    _ListenerService_GetListeners_Handler,
		},
		{
			MethodName: "GetListenersByEnvironment",
			Handler:    _ListenerService_GetListenersByEnvironment_Handler,
		},
		{
			MethodName: "UpdateListener",
			Handler:    _ListenerService_UpdateListener_Handler,
		},
		{
			MethodName: "DeleteListener",
			Handler:    _ListenerService_DeleteListener_Handler,
		},
		{
			MethodName: "MapListenerToEnvironment",
			Handler:    _ListenerService_MapListenerToEnvironment_Handler,
		},
		{
			MethodName: "UnmapListenerFromEnvironment",
			Handler:    _ListenerService_UnmapListenerFromEnvironment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/listener.proto",
}
