// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: merionyx/gateway/auth/v1/gateway_auth.proto

// Renamed from auth.proto: global protobuf registry path must be unique;
// go.etcd.io/etcd/api/v3/authpb also registers "auth.proto".

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContractAccess access to a contract
type ContractAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractName  string                 `protobuf:"bytes,1,opt,name=contract_name,json=contractName,proto3" json:"contract_name,omitempty"`
	Secure        bool                   `protobuf:"varint,2,opt,name=secure,proto3" json:"secure,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Apps          []*AppAccess           `protobuf:"bytes,4,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractAccess) Reset() {
	*x = ContractAccess{}
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractAccess) ProtoMessage() {}

func (x *ContractAccess) ProtoReflect() protoreflect.Message {
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractAccess.ProtoReflect.Descriptor instead.
func (*ContractAccess) Descriptor() ([]byte, []int) {
	return file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ContractAccess) GetContractName() string {
	if x != nil {
		return x.ContractName
	}
	return ""
}

func (x *ContractAccess) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *ContractAccess) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ContractAccess) GetApps() []*AppAccess {
	if x != nil {
		return x.Apps
	}
	return nil
}

// AppAccess access to an application
type AppAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Environments  []string               `protobuf:"bytes,2,rep,name=environments,proto3" json:"environments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppAccess) Reset() {
	*x = AppAccess{}
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppAccess) ProtoMessage() {}

func (x *AppAccess) ProtoReflect() protoreflect.Message {
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppAccess.ProtoReflect.Descriptor instead.
func (*AppAccess) Descriptor() ([]byte, []int) {
	return file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AppAccess) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppAccess) GetEnvironments() []string {
	if x != nil {
		return x.Environments
	}
	return nil
}

// AccessConfig full access configuration for an environment
type AccessConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   string                 `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	Contracts     []*ContractAccess      `protobuf:"bytes,2,rep,name=contracts,proto3" json:"contracts,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // Configuration version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessConfig) Reset() {
	*x = AccessConfig{}
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessConfig) ProtoMessage() {}

func (x *AccessConfig) ProtoReflect() protoreflect.Message {
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessConfig.ProtoReflect.Descriptor instead.
func (*AccessConfig) Descriptor() ([]byte, []int) {
	return file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AccessConfig) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *AccessConfig) GetContracts() []*ContractAccess {
	if x != nil {
		return x.Contracts
	}
	return nil
}

func (x *AccessConfig) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// SyncAccessRequest request to synchronize
type SyncAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   string                 `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	SidecarId     string                 `protobuf:"bytes,2,opt,name=sidecar_id,json=sidecarId,proto3" json:"sidecar_id,omitempty"` // Unique sidecar ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAccessRequest) Reset() {
	*x = SyncAccessRequest{}
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAccessRequest) ProtoMessage() {}

func (x *SyncAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAccessRequest.ProtoReflect.Descriptor instead.
func (*SyncAccessRequest) Descriptor() ([]byte, []int) {
	return file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SyncAccessRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *SyncAccessRequest) GetSidecarId() string {
	if x != nil {
		return x.SidecarId
	}
	return ""
}

// SyncAccessResponse response with configuration
type SyncAccessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*SyncAccessResponse_InitialConfig
	//	*SyncAccessResponse_Update
	//	*SyncAccessResponse_Heartbeat
	Message       isSyncAccessResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAccessResponse) Reset() {
	*x = SyncAccessResponse{}
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAccessResponse) ProtoMessage() {}

func (x *SyncAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAccessResponse.ProtoReflect.Descriptor instead.
func (*SyncAccessResponse) Descriptor() ([]byte, []int) {
	return file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SyncAccessResponse) GetMessage() isSyncAccessResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SyncAccessResponse) GetInitialConfig() *AccessConfig {
	if x != nil {
		if x, ok := x.Message.(*SyncAccessResponse_InitialConfig); ok {
			return x.InitialConfig
		}
	}
	return nil
}

func (x *SyncAccessResponse) GetUpdate() *AccessUpdate {
	if x != nil {
		if x, ok := x.Message.(*SyncAccessResponse_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *SyncAccessResponse) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*SyncAccessResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isSyncAccessResponse_Message interface {
	isSyncAccessResponse_Message()
}

type SyncAccessResponse_InitialConfig struct {
	InitialConfig *AccessConfig `protobuf:"bytes,1,opt,name=initial_config,json=initialConfig,proto3,oneof"` // Initial configuration
}

type SyncAccessResponse_Update struct {
	Update *AccessUpdate `protobuf:"bytes,2,opt,name=update,proto3,oneof"` // Incremental update
}

type SyncAccessResponse_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"` // Heartbeat for keep-alive
}

func (*SyncAccessResponse_InitialConfig) isSyncAccessResponse_Message() {}

func (*SyncAccessResponse_Update) isSyncAccessResponse_Message() {}

func (*SyncAccessResponse_Heartbeat) isSyncAccessResponse_Message() {}

// AccessUpdate incremental update
type AccessUpdate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Environment      string                 `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	AddedContracts   []*ContractAccess      `protobuf:"bytes,2,rep,name=added_contracts,json=addedContracts,proto3" json:"added_contracts,omitempty"`
	UpdatedContracts []*ContractAccess      `protobuf:"bytes,3,rep,name=updated_contracts,json=updatedContracts,proto3" json:"updated_contracts,omitempty"`
	RemovedContracts []string               `protobuf:"bytes,4,rep,name=removed_contracts,json=removedContracts,proto3" json:"removed_contracts,omitempty"` // Contract names
	Version          int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccessUpdate) Reset() {
	*x = AccessUpdate{}
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessUpdate) ProtoMessage() {}

func (x *AccessUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessUpdate.ProtoReflect.Descriptor instead.
func (*AccessUpdate) Descriptor() ([]byte, []int) {
	return file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescGZIP(), []int{5}
}

func (x *AccessUpdate) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *AccessUpdate) GetAddedContracts() []*ContractAccess {
	if x != nil {
		return x.AddedContracts
	}
	return nil
}

func (x *AccessUpdate) GetUpdatedContracts() []*ContractAccess {
	if x != nil {
		return x.UpdatedContracts
	}
	return nil
}

func (x *AccessUpdate) GetRemovedContracts() []string {
	if x != nil {
		return x.RemovedContracts
	}
	return nil
}

func (x *AccessUpdate) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Heartbeat for keeping the connection alive
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// GetAccessConfigRequest request for configuration
type GetAccessConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   string                 `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessConfigRequest) Reset() {
	*x = GetAccessConfigRequest{}
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessConfigRequest) ProtoMessage() {}

func (x *GetAccessConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessConfigRequest.ProtoReflect.Descriptor instead.
func (*GetAccessConfigRequest) Descriptor() ([]byte, []int) {
	return file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccessConfigRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

type GetAccessConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AccessConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessConfigResponse) Reset() {
	*x = GetAccessConfigResponse{}
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessConfigResponse) ProtoMessage() {}

func (x *GetAccessConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessConfigResponse.ProtoReflect.Descriptor instead.
func (*GetAccessConfigResponse) Descriptor() ([]byte, []int) {
	return file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescGZIP(), []int{8}
}

func (x *GetAccessConfigResponse) GetConfig() *AccessConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_merionyx_gateway_auth_v1_gateway_auth_proto protoreflect.FileDescriptor

const file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDesc = "" +
	"\n" +
	"+merionyx/gateway/auth/v1/gateway_auth.proto\x12\x18merionyx.gateway.auth.v1\"\x9e\x01\n" +
	"\x0eContractAccess\x12#\n" +
	"\rcontract_name\x18\x01 \x01(\tR\fcontractName\x12\x16\n" +
	"\x06secure\x18\x02 \x01(\bR\x06secure\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x127\n" +
	"\x04apps\x18\x04 \x03(\v2#.merionyx.gateway.auth.v1.AppAccessR\x04apps\"F\n" +
	"\tAppAccess\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\"\n" +
	"\fenvironments\x18\x02 \x03(\tR\fenvironments\"\x92\x01\n" +
	"\fAccessConfig\x12 \n" +
	"\venvironment\x18\x01 \x01(\tR\venvironment\x12F\n" +
	"\tcontracts\x18\x02 \x03(\v2(.merionyx.gateway.auth.v1.ContractAccessR\tcontracts\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"T\n" +
	"\x11SyncAccessRequest\x12 \n" +
	"\venvironment\x18\x01 \x01(\tR\venvironment\x12\x1d\n" +
	"\n" +
	"sidecar_id\x18\x02 \x01(\tR\tsidecarId\"\xf7\x01\n" +
	"\x12SyncAccessResponse\x12O\n" +
	"\x0einitial_config\x18\x01 \x01(\v2&.merionyx.gateway.auth.v1.AccessConfigH\x00R\rinitialConfig\x12@\n" +
	"\x06update\x18\x02 \x01(\v2&.merionyx.gateway.auth.v1.AccessUpdateH\x00R\x06update\x12C\n" +
	"\theartbeat\x18\x03 \x01(\v2#.merionyx.gateway.auth.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\amessage\"\xa1\x02\n" +
	"\fAccessUpdate\x12 \n" +
	"\venvironment\x18\x01 \x01(\tR\venvironment\x12Q\n" +
	"\x0fadded_contracts\x18\x02 \x03(\v2(.merionyx.gateway.auth.v1.ContractAccessR\x0eaddedContracts\x12U\n" +
	"\x11updated_contracts\x18\x03 \x03(\v2(.merionyx.gateway.auth.v1.ContractAccessR\x10updatedContracts\x12+\n" +
	"\x11removed_contracts\x18\x04 \x03(\tR\x10removedContracts\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\":\n" +
	"\x16GetAccessConfigRequest\x12 \n" +
	"\venvironment\x18\x01 \x01(\tR\venvironment\"Y\n" +
	"\x17GetAccessConfigResponse\x12>\n" +
	"\x06config\x18\x01 \x01(\v2&.merionyx.gateway.auth.v1.AccessConfigR\x06config2\xf2\x01\n" +
	"\vAuthService\x12k\n" +
	"\n" +
	"SyncAccess\x12+.merionyx.gateway.auth.v1.SyncAccessRequest\x1a,.merionyx.gateway.auth.v1.SyncAccessResponse(\x010\x01\x12v\n" +
	"\x0fGetAccessConfig\x120.merionyx.gateway.auth.v1.GetAccessConfigRequest\x1a1.merionyx.gateway.auth.v1.GetAccessConfigResponseB9Z7github.com/merionyx/api-gateway/pkg/grpc/auth/v1;authv1b\x06proto3"

var (
	file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescOnce sync.Once
	file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescData []byte
)

func file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescGZIP() []byte {
	file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescOnce.Do(func() {
		file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDesc), len(file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDesc)))
	})
	return file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDescData
}

var file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_merionyx_gateway_auth_v1_gateway_auth_proto_goTypes = []any{
	(*ContractAccess)(nil),          // 0: merionyx.gateway.auth.v1.ContractAccess
	(*AppAccess)(nil),               // 1: merionyx.gateway.auth.v1.AppAccess
	(*AccessConfig)(nil),            // 2: merionyx.gateway.auth.v1.AccessConfig
	(*SyncAccessRequest)(nil),       // 3: merionyx.gateway.auth.v1.SyncAccessRequest
	(*SyncAccessResponse)(nil),      // 4: merionyx.gateway.auth.v1.SyncAccessResponse
	(*AccessUpdate)(nil),            // 5: merionyx.gateway.auth.v1.AccessUpdate
	(*Heartbeat)(nil),               // 6: merionyx.gateway.auth.v1.Heartbeat
	(*GetAccessConfigRequest)(nil),  // 7: merionyx.gateway.auth.v1.GetAccessConfigRequest
	(*GetAccessConfigResponse)(nil), // 8: merionyx.gateway.auth.v1.GetAccessConfigResponse
}
var file_merionyx_gateway_auth_v1_gateway_auth_proto_depIdxs = []int32{
	1,  // 0: merionyx.gateway.auth.v1.ContractAccess.apps:type_name -> merionyx.gateway.auth.v1.AppAccess
	0,  // 1: merionyx.gateway.auth.v1.AccessConfig.contracts:type_name -> merionyx.gateway.auth.v1.ContractAccess
	2,  // 2: merionyx.gateway.auth.v1.SyncAccessResponse.initial_config:type_name -> merionyx.gateway.auth.v1.AccessConfig
	5,  // 3: merionyx.gateway.auth.v1.SyncAccessResponse.update:type_name -> merionyx.gateway.auth.v1.AccessUpdate
	6,  // 4: merionyx.gateway.auth.v1.SyncAccessResponse.heartbeat:type_name -> merionyx.gateway.auth.v1.Heartbeat
	0,  // 5: merionyx.gateway.auth.v1.AccessUpdate.added_contracts:type_name -> merionyx.gateway.auth.v1.ContractAccess
	0,  // 6: merionyx.gateway.auth.v1.AccessUpdate.updated_contracts:type_name -> merionyx.gateway.auth.v1.ContractAccess
	2,  // 7: merionyx.gateway.auth.v1.GetAccessConfigResponse.config:type_name -> merionyx.gateway.auth.v1.AccessConfig
	3,  // 8: merionyx.gateway.auth.v1.AuthService.SyncAccess:input_type -> merionyx.gateway.auth.v1.SyncAccessRequest
	7,  // 9: merionyx.gateway.auth.v1.AuthService.GetAccessConfig:input_type -> merionyx.gateway.auth.v1.GetAccessConfigRequest
	4,  // 10: merionyx.gateway.auth.v1.AuthService.SyncAccess:output_type -> merionyx.gateway.auth.v1.SyncAccessResponse
	8,  // 11: merionyx.gateway.auth.v1.AuthService.GetAccessConfig:output_type -> merionyx.gateway.auth.v1.GetAccessConfigResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_merionyx_gateway_auth_v1_gateway_auth_proto_init() }
func file_merionyx_gateway_auth_v1_gateway_auth_proto_init() {
	if File_merionyx_gateway_auth_v1_gateway_auth_proto != nil {
		return
	}
	file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes[4].OneofWrappers = []any{
		(*SyncAccessResponse_InitialConfig)(nil),
		(*SyncAccessResponse_Update)(nil),
		(*SyncAccessResponse_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDesc), len(file_merionyx_gateway_auth_v1_gateway_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merionyx_gateway_auth_v1_gateway_auth_proto_goTypes,
		DependencyIndexes: file_merionyx_gateway_auth_v1_gateway_auth_proto_depIdxs,
		MessageInfos:      file_merionyx_gateway_auth_v1_gateway_auth_proto_msgTypes,
	}.Build()
	File_merionyx_gateway_auth_v1_gateway_auth_proto = out.File
	file_merionyx_gateway_auth_v1_gateway_auth_proto_goTypes = nil
	file_merionyx_gateway_auth_v1_gateway_auth_proto_depIdxs = nil
}
