networks:
  default:

services:
  envoy-dev:
    image: envoyproxy/envoy:v1.33-latest
    container_name: envoy-dev
    volumes:
      - ./configs/envoy/dev.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "10000:10000"
      - "9901:9901"
    command: ["-c", "/etc/envoy/envoy.yaml"]
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - app
  envoy-prod:
    image: envoyproxy/envoy:v1.33-latest
    container_name: envoy-prod
    volumes:
      - ./configs/envoy/prod.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "10001:10000"
      - "9902:9902"
    command: ["-c", "/etc/envoy/envoy.yaml"]
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - app
