networks:
  default:
  auth-sidecar-dev:
    external: true
  auth-sidecar-prod:
    external: true

services:
  envoy-dev-01:
    image: envoyproxy/envoy:v1.33-latest
    container_name: envoy-dev-01
    volumes:
      - ./configs/envoy/dev.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "10000:10000"
      - "9901:9901"
    command: ["-c", "/etc/envoy/envoy.yaml"]
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - gateway-controller
      - auth-sidecar-dev
  envoy-dev-02:
    image: envoyproxy/envoy:v1.33-latest
    container_name: envoy-dev-02
    volumes:
      - ./configs/envoy/dev.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "10001:10000"
      - "9902:9901"
    command: ["-c", "/etc/envoy/envoy.yaml"]
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - gateway-controller
      - auth-sidecar-dev
  envoy-prod-01:
    image: envoyproxy/envoy:v1.33-latest
    container_name: envoy-prod-01
    volumes:
      - ./configs/envoy/prod.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "10002:10000"
      - "9903:9902"
    command: ["-c", "/etc/envoy/envoy.yaml"]
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - gateway-controller
      - auth-sidecar-prod
  envoy-prod-02:
    image: envoyproxy/envoy:v1.33-latest
    container_name: envoy-prod-02
    volumes:
      - ./configs/envoy/prod.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "10003:10000"
      - "9904:9902"
    command: ["-c", "/etc/envoy/envoy.yaml"]
    restart: unless-stopped
    networks:
      - default
    depends_on:
      - gateway-controller
      - auth-sidecar-prod
