networks:
    default:

services:
    app:
        container_name: merionyx-api-gateway-control-plane
        build:
            context: ../..
            dockerfile: Dockerfile.dev
        command: air -c .air.toml
        environment:
            - CONFIG_FILE=./configs/control-plane/config.yaml
        ports:
            - 8080:8080
            - 8443:8443
            - 8090:8090
        develop:
            watch:
                - path: ../..
                  target: /app
                  action: sync
                  ignore:
                      - .air.toml
                      - .gitignore
                      - .git
                      - .github
                      - .vscode
                      - .env
                      - .env.example
                      - .env.local
                      - .env.development
                      - .env.production
        networks:
            - default
