networks:
    default:

services:
    control-plane:
        container_name: merionyx-api-gateway-control-plane
        build:
            context: ../..
            dockerfile: Dockerfile.dev
        command: air -c .air.toml
        environment:
            - CONFIG_FILE=./configs/control-plane/config.yaml
            - SSH_KNOWN_HOSTS=/app/secrets/known_hosts
        env_file:
            - ../../secrets/.env
        ports:
            - 9080:8080
            - 9443:8443
            - 19090:19090
            - 19091:19091
        develop:
            watch:
                - path: ../..
                  target: /app
                  action: sync
                  ignore:
                      - .air.toml
                      - .gitignore
                      - .git
                      - .github
                      - .vscode
                      - .env
                      - .env.example
                      - .env.local
                      - .env.development
                      - .env.production
        networks:
            - default
        depends_on:
            - etcd
