// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: controller_registry.proto

package controllerregistryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "merionyx/api-gateway/pkg/api/contract/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterControllerRequest registers a Gateway Controller with the API Server.
// environments is the full snapshot of environments this controller declares (static + K8s + etcd CRUD merge);
// it is not a delta.
type RegisterControllerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControllerId  string                 `protobuf:"bytes,1,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Environments  []*EnvironmentInfo     `protobuf:"bytes,3,rep,name=environments,proto3" json:"environments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterControllerRequest) Reset() {
	*x = RegisterControllerRequest{}
	mi := &file_controller_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterControllerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterControllerRequest) ProtoMessage() {}

func (x *RegisterControllerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterControllerRequest.ProtoReflect.Descriptor instead.
func (*RegisterControllerRequest) Descriptor() ([]byte, []int) {
	return file_controller_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterControllerRequest) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

func (x *RegisterControllerRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *RegisterControllerRequest) GetEnvironments() []*EnvironmentInfo {
	if x != nil {
		return x.Environments
	}
	return nil
}

// EnvironmentInfo information about environment
type EnvironmentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bundles       []*BundleInfo          `protobuf:"bytes,2,rep,name=bundles,proto3" json:"bundles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentInfo) Reset() {
	*x = EnvironmentInfo{}
	mi := &file_controller_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentInfo) ProtoMessage() {}

func (x *EnvironmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_controller_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentInfo.ProtoReflect.Descriptor instead.
func (*EnvironmentInfo) Descriptor() ([]byte, []int) {
	return file_controller_registry_proto_rawDescGZIP(), []int{1}
}

func (x *EnvironmentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvironmentInfo) GetBundles() []*BundleInfo {
	if x != nil {
		return x.Bundles
	}
	return nil
}

// BundleInfo information about bundle
type BundleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Repository    string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Ref           string                 `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleInfo) Reset() {
	*x = BundleInfo{}
	mi := &file_controller_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleInfo) ProtoMessage() {}

func (x *BundleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_controller_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleInfo.ProtoReflect.Descriptor instead.
func (*BundleInfo) Descriptor() ([]byte, []int) {
	return file_controller_registry_proto_rawDescGZIP(), []int{2}
}

func (x *BundleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BundleInfo) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *BundleInfo) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *BundleInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// RegisterControllerResponse response to registration
type RegisterControllerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterControllerResponse) Reset() {
	*x = RegisterControllerResponse{}
	mi := &file_controller_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterControllerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterControllerResponse) ProtoMessage() {}

func (x *RegisterControllerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterControllerResponse.ProtoReflect.Descriptor instead.
func (*RegisterControllerResponse) Descriptor() ([]byte, []int) {
	return file_controller_registry_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterControllerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterControllerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StreamSnapshotsRequest request to stream snapshots
type StreamSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControllerId  string                 `protobuf:"bytes,1,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSnapshotsRequest) Reset() {
	*x = StreamSnapshotsRequest{}
	mi := &file_controller_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSnapshotsRequest) ProtoMessage() {}

func (x *StreamSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*StreamSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_controller_registry_proto_rawDescGZIP(), []int{4}
}

func (x *StreamSnapshotsRequest) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

// StreamSnapshotsResponse stream snapshots for controller
type StreamSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   string                 `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	BundleKey     string                 `protobuf:"bytes,2,opt,name=bundle_key,json=bundleKey,proto3" json:"bundle_key,omitempty"`
	Snapshots     []*v1.ContractSnapshot `protobuf:"bytes,3,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSnapshotsResponse) Reset() {
	*x = StreamSnapshotsResponse{}
	mi := &file_controller_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSnapshotsResponse) ProtoMessage() {}

func (x *StreamSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*StreamSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_controller_registry_proto_rawDescGZIP(), []int{5}
}

func (x *StreamSnapshotsResponse) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *StreamSnapshotsResponse) GetBundleKey() string {
	if x != nil {
		return x.BundleKey
	}
	return ""
}

func (x *StreamSnapshotsResponse) GetSnapshots() []*v1.ContractSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

// HeartbeatRequest periodic update from controller.
// environments must be the full current snapshot (same semantics as RegisterControllerRequest.environments).
// The API Server replaces the stored controller record's environment list with this payload (not a merge/delta).
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControllerId  string                 `protobuf:"bytes,1,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	Environments  []*EnvironmentInfo     `protobuf:"bytes,2,rep,name=environments,proto3" json:"environments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_controller_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controller_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_controller_registry_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetControllerId() string {
	if x != nil {
		return x.ControllerId
	}
	return ""
}

func (x *HeartbeatRequest) GetEnvironments() []*EnvironmentInfo {
	if x != nil {
		return x.Environments
	}
	return nil
}

// HeartbeatResponse response to heartbeat
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_controller_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controller_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_controller_registry_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_controller_registry_proto protoreflect.FileDescriptor

const file_controller_registry_proto_rawDesc = "" +
	"\n" +
	"\x19controller_registry.proto\x12\x1aapi.controller_registry.v1\x1a\x14contract_types.proto\"\xa9\x01\n" +
	"\x19RegisterControllerRequest\x12#\n" +
	"\rcontroller_id\x18\x01 \x01(\tR\fcontrollerId\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12O\n" +
	"\fenvironments\x18\x03 \x03(\v2+.api.controller_registry.v1.EnvironmentInfoR\fenvironments\"g\n" +
	"\x0fEnvironmentInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12@\n" +
	"\abundles\x18\x02 \x03(\v2&.api.controller_registry.v1.BundleInfoR\abundles\"f\n" +
	"\n" +
	"BundleInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"L\n" +
	"\x1aRegisterControllerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"=\n" +
	"\x16StreamSnapshotsRequest\x12#\n" +
	"\rcontroller_id\x18\x01 \x01(\tR\fcontrollerId\"\x9b\x01\n" +
	"\x17StreamSnapshotsResponse\x12 \n" +
	"\venvironment\x18\x01 \x01(\tR\venvironment\x12\x1d\n" +
	"\n" +
	"bundle_key\x18\x02 \x01(\tR\tbundleKey\x12?\n" +
	"\tsnapshots\x18\x03 \x03(\v2!.api.contract.v1.ContractSnapshotR\tsnapshots\"\x88\x01\n" +
	"\x10HeartbeatRequest\x12#\n" +
	"\rcontroller_id\x18\x01 \x01(\tR\fcontrollerId\x12O\n" +
	"\fenvironments\x18\x02 \x03(\v2+.api.controller_registry.v1.EnvironmentInfoR\fenvironments\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x89\x03\n" +
	"\x19ControllerRegistryService\x12\x83\x01\n" +
	"\x12RegisterController\x125.api.controller_registry.v1.RegisterControllerRequest\x1a6.api.controller_registry.v1.RegisterControllerResponse\x12|\n" +
	"\x0fStreamSnapshots\x122.api.controller_registry.v1.StreamSnapshotsRequest\x1a3.api.controller_registry.v1.StreamSnapshotsResponse0\x01\x12h\n" +
	"\tHeartbeat\x12,.api.controller_registry.v1.HeartbeatRequest\x1a-.api.controller_registry.v1.HeartbeatResponseBUZSmerionyx/api-gateway/controller/pkg/api/controller_registry/v1;controllerregistryv1b\x06proto3"

var (
	file_controller_registry_proto_rawDescOnce sync.Once
	file_controller_registry_proto_rawDescData []byte
)

func file_controller_registry_proto_rawDescGZIP() []byte {
	file_controller_registry_proto_rawDescOnce.Do(func() {
		file_controller_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controller_registry_proto_rawDesc), len(file_controller_registry_proto_rawDesc)))
	})
	return file_controller_registry_proto_rawDescData
}

var file_controller_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_controller_registry_proto_goTypes = []any{
	(*RegisterControllerRequest)(nil),  // 0: api.controller_registry.v1.RegisterControllerRequest
	(*EnvironmentInfo)(nil),            // 1: api.controller_registry.v1.EnvironmentInfo
	(*BundleInfo)(nil),                 // 2: api.controller_registry.v1.BundleInfo
	(*RegisterControllerResponse)(nil), // 3: api.controller_registry.v1.RegisterControllerResponse
	(*StreamSnapshotsRequest)(nil),     // 4: api.controller_registry.v1.StreamSnapshotsRequest
	(*StreamSnapshotsResponse)(nil),    // 5: api.controller_registry.v1.StreamSnapshotsResponse
	(*HeartbeatRequest)(nil),           // 6: api.controller_registry.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 7: api.controller_registry.v1.HeartbeatResponse
	(*v1.ContractSnapshot)(nil),        // 8: api.contract.v1.ContractSnapshot
}
var file_controller_registry_proto_depIdxs = []int32{
	1, // 0: api.controller_registry.v1.RegisterControllerRequest.environments:type_name -> api.controller_registry.v1.EnvironmentInfo
	2, // 1: api.controller_registry.v1.EnvironmentInfo.bundles:type_name -> api.controller_registry.v1.BundleInfo
	8, // 2: api.controller_registry.v1.StreamSnapshotsResponse.snapshots:type_name -> api.contract.v1.ContractSnapshot
	1, // 3: api.controller_registry.v1.HeartbeatRequest.environments:type_name -> api.controller_registry.v1.EnvironmentInfo
	0, // 4: api.controller_registry.v1.ControllerRegistryService.RegisterController:input_type -> api.controller_registry.v1.RegisterControllerRequest
	4, // 5: api.controller_registry.v1.ControllerRegistryService.StreamSnapshots:input_type -> api.controller_registry.v1.StreamSnapshotsRequest
	6, // 6: api.controller_registry.v1.ControllerRegistryService.Heartbeat:input_type -> api.controller_registry.v1.HeartbeatRequest
	3, // 7: api.controller_registry.v1.ControllerRegistryService.RegisterController:output_type -> api.controller_registry.v1.RegisterControllerResponse
	5, // 8: api.controller_registry.v1.ControllerRegistryService.StreamSnapshots:output_type -> api.controller_registry.v1.StreamSnapshotsResponse
	7, // 9: api.controller_registry.v1.ControllerRegistryService.Heartbeat:output_type -> api.controller_registry.v1.HeartbeatResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_controller_registry_proto_init() }
func file_controller_registry_proto_init() {
	if File_controller_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_registry_proto_rawDesc), len(file_controller_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controller_registry_proto_goTypes,
		DependencyIndexes: file_controller_registry_proto_depIdxs,
		MessageInfos:      file_controller_registry_proto_msgTypes,
	}.Build()
	File_controller_registry_proto = out.File
	file_controller_registry_proto_goTypes = nil
	file_controller_registry_proto_depIdxs = nil
}
