// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/v1/tenant.proto

package tenantv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tenant message for tenant
type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_api_proto_v1_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tenant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateTenantRequest request for creating tenant
type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_api_proto_v1_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// CreateTenantResponse response for creating tenant
type CreateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantResponse) Reset() {
	*x = CreateTenantResponse{}
	mi := &file_api_proto_v1_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantResponse) ProtoMessage() {}

func (x *CreateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantResponse.ProtoReflect.Descriptor instead.
func (*CreateTenantResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

// GetTenantRequest request for getting tenant
type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_api_proto_v1_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *GetTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetTenantResponse response for getting tenant
type GetTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantResponse) Reset() {
	*x = GetTenantResponse{}
	mi := &file_api_proto_v1_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantResponse) ProtoMessage() {}

func (x *GetTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantResponse.ProtoReflect.Descriptor instead.
func (*GetTenantResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *GetTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

// GetTenantByNameRequest request for getting tenant by name
type GetTenantByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantByNameRequest) Reset() {
	*x = GetTenantByNameRequest{}
	mi := &file_api_proto_v1_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantByNameRequest) ProtoMessage() {}

func (x *GetTenantByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantByNameRequest.ProtoReflect.Descriptor instead.
func (*GetTenantByNameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *GetTenantByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetTenantByNameResponse response for getting tenant by name
type GetTenantByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantByNameResponse) Reset() {
	*x = GetTenantByNameResponse{}
	mi := &file_api_proto_v1_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantByNameResponse) ProtoMessage() {}

func (x *GetTenantByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantByNameResponse.ProtoReflect.Descriptor instead.
func (*GetTenantByNameResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *GetTenantByNameResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

// GetTenantsRequest request for getting list of tenants
type GetTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantsRequest) Reset() {
	*x = GetTenantsRequest{}
	mi := &file_api_proto_v1_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantsRequest) ProtoMessage() {}

func (x *GetTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantsRequest.ProtoReflect.Descriptor instead.
func (*GetTenantsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tenant_proto_rawDescGZIP(), []int{7}
}

// GetTenantsResponse response for getting list of tenants
type GetTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*Tenant              `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantsResponse) Reset() {
	*x = GetTenantsResponse{}
	mi := &file_api_proto_v1_tenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantsResponse) ProtoMessage() {}

func (x *GetTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantsResponse.ProtoReflect.Descriptor instead.
func (*GetTenantsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tenant_proto_rawDescGZIP(), []int{8}
}

func (x *GetTenantsResponse) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

// UpdateTenantRequest request for updating tenant
type UpdateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantRequest) Reset() {
	*x = UpdateTenantRequest{}
	mi := &file_api_proto_v1_tenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantRequest) ProtoMessage() {}

func (x *UpdateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tenant_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// UpdateTenantResponse response for updating tenant
type UpdateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantResponse) Reset() {
	*x = UpdateTenantResponse{}
	mi := &file_api_proto_v1_tenant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantResponse) ProtoMessage() {}

func (x *UpdateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tenant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantResponse.ProtoReflect.Descriptor instead.
func (*UpdateTenantResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tenant_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

// DeleteTenantRequest request for deleting tenant
type DeleteTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_api_proto_v1_tenant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tenant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tenant_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteTenantResponse response for deleting tenant
type DeleteTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantResponse) Reset() {
	*x = DeleteTenantResponse{}
	mi := &file_api_proto_v1_tenant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantResponse) ProtoMessage() {}

func (x *DeleteTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_tenant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantResponse.ProtoReflect.Descriptor instead.
func (*DeleteTenantResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_tenant_proto_rawDescGZIP(), []int{12}
}

var File_api_proto_v1_tenant_proto protoreflect.FileDescriptor

const file_api_proto_v1_tenant_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/v1/tenant.proto\x12\rapi.tenant.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\")\n" +
	"\x13CreateTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"E\n" +
	"\x14CreateTenantResponse\x12-\n" +
	"\x06tenant\x18\x01 \x01(\v2\x15.api.tenant.v1.TenantR\x06tenant\"\"\n" +
	"\x10GetTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x11GetTenantResponse\x12-\n" +
	"\x06tenant\x18\x01 \x01(\v2\x15.api.tenant.v1.TenantR\x06tenant\",\n" +
	"\x16GetTenantByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"H\n" +
	"\x17GetTenantByNameResponse\x12-\n" +
	"\x06tenant\x18\x01 \x01(\v2\x15.api.tenant.v1.TenantR\x06tenant\"\x13\n" +
	"\x11GetTenantsRequest\"E\n" +
	"\x12GetTenantsResponse\x12/\n" +
	"\atenants\x18\x01 \x03(\v2\x15.api.tenant.v1.TenantR\atenants\"9\n" +
	"\x13UpdateTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"E\n" +
	"\x14UpdateTenantResponse\x12-\n" +
	"\x06tenant\x18\x01 \x01(\v2\x15.api.tenant.v1.TenantR\x06tenant\"%\n" +
	"\x13DeleteTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteTenantResponse2\x9f\x04\n" +
	"\rTenantService\x12W\n" +
	"\fCreateTenant\x12\".api.tenant.v1.CreateTenantRequest\x1a#.api.tenant.v1.CreateTenantResponse\x12N\n" +
	"\tGetTenant\x12\x1f.api.tenant.v1.GetTenantRequest\x1a .api.tenant.v1.GetTenantResponse\x12`\n" +
	"\x0fGetTenantByName\x12%.api.tenant.v1.GetTenantByNameRequest\x1a&.api.tenant.v1.GetTenantByNameResponse\x12Q\n" +
	"\n" +
	"GetTenants\x12 .api.tenant.v1.GetTenantsRequest\x1a!.api.tenant.v1.GetTenantsResponse\x12W\n" +
	"\fUpdateTenant\x12\".api.tenant.v1.UpdateTenantRequest\x1a#.api.tenant.v1.UpdateTenantResponse\x12W\n" +
	"\fDeleteTenant\x12\".api.tenant.v1.DeleteTenantRequest\x1a#.api.tenant.v1.DeleteTenantResponseB\x18Z\x16api/tenant/v1;tenantv1b\x06proto3"

var (
	file_api_proto_v1_tenant_proto_rawDescOnce sync.Once
	file_api_proto_v1_tenant_proto_rawDescData []byte
)

func file_api_proto_v1_tenant_proto_rawDescGZIP() []byte {
	file_api_proto_v1_tenant_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_tenant_proto_rawDesc), len(file_api_proto_v1_tenant_proto_rawDesc)))
	})
	return file_api_proto_v1_tenant_proto_rawDescData
}

var file_api_proto_v1_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_proto_v1_tenant_proto_goTypes = []any{
	(*Tenant)(nil),                  // 0: api.tenant.v1.Tenant
	(*CreateTenantRequest)(nil),     // 1: api.tenant.v1.CreateTenantRequest
	(*CreateTenantResponse)(nil),    // 2: api.tenant.v1.CreateTenantResponse
	(*GetTenantRequest)(nil),        // 3: api.tenant.v1.GetTenantRequest
	(*GetTenantResponse)(nil),       // 4: api.tenant.v1.GetTenantResponse
	(*GetTenantByNameRequest)(nil),  // 5: api.tenant.v1.GetTenantByNameRequest
	(*GetTenantByNameResponse)(nil), // 6: api.tenant.v1.GetTenantByNameResponse
	(*GetTenantsRequest)(nil),       // 7: api.tenant.v1.GetTenantsRequest
	(*GetTenantsResponse)(nil),      // 8: api.tenant.v1.GetTenantsResponse
	(*UpdateTenantRequest)(nil),     // 9: api.tenant.v1.UpdateTenantRequest
	(*UpdateTenantResponse)(nil),    // 10: api.tenant.v1.UpdateTenantResponse
	(*DeleteTenantRequest)(nil),     // 11: api.tenant.v1.DeleteTenantRequest
	(*DeleteTenantResponse)(nil),    // 12: api.tenant.v1.DeleteTenantResponse
	(*timestamppb.Timestamp)(nil),   // 13: google.protobuf.Timestamp
}
var file_api_proto_v1_tenant_proto_depIdxs = []int32{
	13, // 0: api.tenant.v1.Tenant.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: api.tenant.v1.Tenant.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: api.tenant.v1.CreateTenantResponse.tenant:type_name -> api.tenant.v1.Tenant
	0,  // 3: api.tenant.v1.GetTenantResponse.tenant:type_name -> api.tenant.v1.Tenant
	0,  // 4: api.tenant.v1.GetTenantByNameResponse.tenant:type_name -> api.tenant.v1.Tenant
	0,  // 5: api.tenant.v1.GetTenantsResponse.tenants:type_name -> api.tenant.v1.Tenant
	0,  // 6: api.tenant.v1.UpdateTenantResponse.tenant:type_name -> api.tenant.v1.Tenant
	1,  // 7: api.tenant.v1.TenantService.CreateTenant:input_type -> api.tenant.v1.CreateTenantRequest
	3,  // 8: api.tenant.v1.TenantService.GetTenant:input_type -> api.tenant.v1.GetTenantRequest
	5,  // 9: api.tenant.v1.TenantService.GetTenantByName:input_type -> api.tenant.v1.GetTenantByNameRequest
	7,  // 10: api.tenant.v1.TenantService.GetTenants:input_type -> api.tenant.v1.GetTenantsRequest
	9,  // 11: api.tenant.v1.TenantService.UpdateTenant:input_type -> api.tenant.v1.UpdateTenantRequest
	11, // 12: api.tenant.v1.TenantService.DeleteTenant:input_type -> api.tenant.v1.DeleteTenantRequest
	2,  // 13: api.tenant.v1.TenantService.CreateTenant:output_type -> api.tenant.v1.CreateTenantResponse
	4,  // 14: api.tenant.v1.TenantService.GetTenant:output_type -> api.tenant.v1.GetTenantResponse
	6,  // 15: api.tenant.v1.TenantService.GetTenantByName:output_type -> api.tenant.v1.GetTenantByNameResponse
	8,  // 16: api.tenant.v1.TenantService.GetTenants:output_type -> api.tenant.v1.GetTenantsResponse
	10, // 17: api.tenant.v1.TenantService.UpdateTenant:output_type -> api.tenant.v1.UpdateTenantResponse
	12, // 18: api.tenant.v1.TenantService.DeleteTenant:output_type -> api.tenant.v1.DeleteTenantResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_v1_tenant_proto_init() }
func file_api_proto_v1_tenant_proto_init() {
	if File_api_proto_v1_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_tenant_proto_rawDesc), len(file_api_proto_v1_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_tenant_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_tenant_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_tenant_proto_msgTypes,
	}.Build()
	File_api_proto_v1_tenant_proto = out.File
	file_api_proto_v1_tenant_proto_goTypes = nil
	file_api_proto_v1_tenant_proto_depIdxs = nil
}
