apiVersion: gateway.merionyx.io/v1alpha1
kind: ContractBundle
metadata:
  name: schemas-bundle-dev
  namespace: default
  labels:
    gateway.merionyx.io/team: demo
spec:
  name: api-gateway-schemas
  repository: api-gateway-schemas-https
  ref: remotes/origin/master
  path: openapi
  environmentRef:
    name: dev
    namespace: default
