{{- if .Values.components.apiServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agwcp.svc.apiServer" . }}
  labels:
    {{- include "agwcp.componentLabels" (list "apiServer" .) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "agwcp.selectorLabels" (list "apiServer" .) | nindent 4 }}
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: grpc
    port: 19093
    targetPort: grpc
  - name: metrics
    port: 9090
    targetPort: metrics
{{- end }}
