{{- if .Values.components.controller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agwcp.serviceAccountName" . }}
  labels:
    {{- include "agwcp.componentLabels" (list "controller" .) | nindent 4 }}
{{- end }}
