server:
  http_port: "8080"
  host: "0.0.0.0"

etcd:
  endpoints:
  - "https://etcd:2379"
  dial_timeout: "5s"
  tls:
    enabled: true
    cert_file: "./secrets/certs/etcd/client.pem"
    key_file: "./secrets/certs/etcd/client-key.pem"
    ca_file: "./secrets/certs/etcd/ca.pem"

jwt:
  keys_dir: "./secrets/api-server/keys/jwt"
  issuer: "gateway-api-server"
