// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: contract_types.proto

package contractv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContractUpstream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractUpstream) Reset() {
	*x = ContractUpstream{}
	mi := &file_contract_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractUpstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractUpstream) ProtoMessage() {}

func (x *ContractUpstream) ProtoReflect() protoreflect.Message {
	mi := &file_contract_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractUpstream.ProtoReflect.Descriptor instead.
func (*ContractUpstream) Descriptor() ([]byte, []int) {
	return file_contract_types_proto_rawDescGZIP(), []int{0}
}

func (x *ContractUpstream) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Environments  []string               `protobuf:"bytes,2,rep,name=environments,proto3" json:"environments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_contract_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_contract_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_contract_types_proto_rawDescGZIP(), []int{1}
}

func (x *App) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *App) GetEnvironments() []string {
	if x != nil {
		return x.Environments
	}
	return nil
}

type Access struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secure        bool                   `protobuf:"varint,1,opt,name=secure,proto3" json:"secure,omitempty"`
	Apps          []*App                 `protobuf:"bytes,2,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Access) Reset() {
	*x = Access{}
	mi := &file_contract_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Access) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Access) ProtoMessage() {}

func (x *Access) ProtoReflect() protoreflect.Message {
	mi := &file_contract_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Access.ProtoReflect.Descriptor instead.
func (*Access) Descriptor() ([]byte, []int) {
	return file_contract_types_proto_rawDescGZIP(), []int{2}
}

func (x *Access) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *Access) GetApps() []*App {
	if x != nil {
		return x.Apps
	}
	return nil
}

type ContractSnapshot struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Prefix                string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Upstream              *ContractUpstream      `protobuf:"bytes,3,opt,name=upstream,proto3" json:"upstream,omitempty"`
	AllowUndefinedMethods bool                   `protobuf:"varint,4,opt,name=allow_undefined_methods,json=allowUndefinedMethods,proto3" json:"allow_undefined_methods,omitempty"`
	Access                *Access                `protobuf:"bytes,5,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ContractSnapshot) Reset() {
	*x = ContractSnapshot{}
	mi := &file_contract_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractSnapshot) ProtoMessage() {}

func (x *ContractSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_contract_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractSnapshot.ProtoReflect.Descriptor instead.
func (*ContractSnapshot) Descriptor() ([]byte, []int) {
	return file_contract_types_proto_rawDescGZIP(), []int{3}
}

func (x *ContractSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContractSnapshot) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ContractSnapshot) GetUpstream() *ContractUpstream {
	if x != nil {
		return x.Upstream
	}
	return nil
}

func (x *ContractSnapshot) GetAllowUndefinedMethods() bool {
	if x != nil {
		return x.AllowUndefinedMethods
	}
	return false
}

func (x *ContractSnapshot) GetAccess() *Access {
	if x != nil {
		return x.Access
	}
	return nil
}

var File_contract_types_proto protoreflect.FileDescriptor

const file_contract_types_proto_rawDesc = "" +
	"\n" +
	"\x14contract_types.proto\x12\x0fapi.contract.v1\"&\n" +
	"\x10ContractUpstream\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"@\n" +
	"\x03App\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\"\n" +
	"\fenvironments\x18\x02 \x03(\tR\fenvironments\"J\n" +
	"\x06Access\x12\x16\n" +
	"\x06secure\x18\x01 \x01(\bR\x06secure\x12(\n" +
	"\x04apps\x18\x02 \x03(\v2\x14.api.contract.v1.AppR\x04apps\"\xe6\x01\n" +
	"\x10ContractSnapshot\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12=\n" +
	"\bupstream\x18\x03 \x01(\v2!.api.contract.v1.ContractUpstreamR\bupstream\x126\n" +
	"\x17allow_undefined_methods\x18\x04 \x01(\bR\x15allowUndefinedMethods\x12/\n" +
	"\x06access\x18\x05 \x01(\v2\x17.api.contract.v1.AccessR\x06accessB5Z3merionyx/api-gateway/pkg/api/contract/v1;contractv1b\x06proto3"

var (
	file_contract_types_proto_rawDescOnce sync.Once
	file_contract_types_proto_rawDescData []byte
)

func file_contract_types_proto_rawDescGZIP() []byte {
	file_contract_types_proto_rawDescOnce.Do(func() {
		file_contract_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_types_proto_rawDesc), len(file_contract_types_proto_rawDesc)))
	})
	return file_contract_types_proto_rawDescData
}

var file_contract_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contract_types_proto_goTypes = []any{
	(*ContractUpstream)(nil), // 0: api.contract.v1.ContractUpstream
	(*App)(nil),              // 1: api.contract.v1.App
	(*Access)(nil),           // 2: api.contract.v1.Access
	(*ContractSnapshot)(nil), // 3: api.contract.v1.ContractSnapshot
}
var file_contract_types_proto_depIdxs = []int32{
	1, // 0: api.contract.v1.Access.apps:type_name -> api.contract.v1.App
	0, // 1: api.contract.v1.ContractSnapshot.upstream:type_name -> api.contract.v1.ContractUpstream
	2, // 2: api.contract.v1.ContractSnapshot.access:type_name -> api.contract.v1.Access
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_contract_types_proto_init() }
func file_contract_types_proto_init() {
	if File_contract_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_types_proto_rawDesc), len(file_contract_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contract_types_proto_goTypes,
		DependencyIndexes: file_contract_types_proto_depIdxs,
		MessageInfos:      file_contract_types_proto_msgTypes,
	}.Build()
	File_contract_types_proto = out.File
	file_contract_types_proto_goTypes = nil
	file_contract_types_proto_depIdxs = nil
}
