// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: contract_syncer.proto

package contractsyncerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "merionyx/api-gateway/pkg/api/contract/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncRequest request to sync snapshots for a specific bundle
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_contract_syncer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_syncer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_contract_syncer_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *SyncRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *SyncRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// SyncResponse response with snapshots for a bundle
type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*v1.ContractSnapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_contract_syncer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_syncer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_contract_syncer_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetSnapshots() []*v1.ContractSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *SyncResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_contract_syncer_proto protoreflect.FileDescriptor

const file_contract_syncer_proto_rawDesc = "" +
	"\n" +
	"\x15contract_syncer.proto\x12\x16api.contract_syncer.v1\x1a\x14contract_types.proto\"S\n" +
	"\vSyncRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"e\n" +
	"\fSyncResponse\x12?\n" +
	"\tsnapshots\x18\x01 \x03(\v2!.api.contract.v1.ContractSnapshotR\tsnapshots\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2j\n" +
	"\x15ContractSyncerService\x12Q\n" +
	"\x04Sync\x12#.api.contract_syncer.v1.SyncRequest\x1a$.api.contract_syncer.v1.SyncResponseBMZKmerionyx/api-gateway/controller/pkg/api/contract_syncer/v1;contractsyncerv1b\x06proto3"

var (
	file_contract_syncer_proto_rawDescOnce sync.Once
	file_contract_syncer_proto_rawDescData []byte
)

func file_contract_syncer_proto_rawDescGZIP() []byte {
	file_contract_syncer_proto_rawDescOnce.Do(func() {
		file_contract_syncer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_syncer_proto_rawDesc), len(file_contract_syncer_proto_rawDesc)))
	})
	return file_contract_syncer_proto_rawDescData
}

var file_contract_syncer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contract_syncer_proto_goTypes = []any{
	(*SyncRequest)(nil),         // 0: api.contract_syncer.v1.SyncRequest
	(*SyncResponse)(nil),        // 1: api.contract_syncer.v1.SyncResponse
	(*v1.ContractSnapshot)(nil), // 2: api.contract.v1.ContractSnapshot
}
var file_contract_syncer_proto_depIdxs = []int32{
	2, // 0: api.contract_syncer.v1.SyncResponse.snapshots:type_name -> api.contract.v1.ContractSnapshot
	0, // 1: api.contract_syncer.v1.ContractSyncerService.Sync:input_type -> api.contract_syncer.v1.SyncRequest
	1, // 2: api.contract_syncer.v1.ContractSyncerService.Sync:output_type -> api.contract_syncer.v1.SyncResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contract_syncer_proto_init() }
func file_contract_syncer_proto_init() {
	if File_contract_syncer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_syncer_proto_rawDesc), len(file_contract_syncer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_syncer_proto_goTypes,
		DependencyIndexes: file_contract_syncer_proto_depIdxs,
		MessageInfos:      file_contract_syncer_proto_msgTypes,
	}.Build()
	File_contract_syncer_proto = out.File
	file_contract_syncer_proto_goTypes = nil
	file_contract_syncer_proto_depIdxs = nil
}
