// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/v1/contract_syncer.proto

package contractsyncerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncRequest request to sync snapshots for a specific bundle
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_api_proto_v1_contract_syncer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_contract_syncer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_contract_syncer_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *SyncRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *SyncRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// SyncResponse response with snapshots for a bundle
type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*ContractSnapshot    `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_proto_v1_contract_syncer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_contract_syncer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_contract_syncer_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetSnapshots() []*ContractSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *SyncResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ContractSnapshot represents a contract snapshot
type ContractSnapshot struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Prefix                string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Upstream              *ContractUpstream      `protobuf:"bytes,3,opt,name=upstream,proto3" json:"upstream,omitempty"`
	AllowUndefinedMethods bool                   `protobuf:"varint,4,opt,name=allow_undefined_methods,json=allowUndefinedMethods,proto3" json:"allow_undefined_methods,omitempty"`
	Access                *Access                `protobuf:"bytes,5,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ContractSnapshot) Reset() {
	*x = ContractSnapshot{}
	mi := &file_api_proto_v1_contract_syncer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractSnapshot) ProtoMessage() {}

func (x *ContractSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_contract_syncer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractSnapshot.ProtoReflect.Descriptor instead.
func (*ContractSnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_contract_syncer_proto_rawDescGZIP(), []int{2}
}

func (x *ContractSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContractSnapshot) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ContractSnapshot) GetUpstream() *ContractUpstream {
	if x != nil {
		return x.Upstream
	}
	return nil
}

func (x *ContractSnapshot) GetAllowUndefinedMethods() bool {
	if x != nil {
		return x.AllowUndefinedMethods
	}
	return false
}

func (x *ContractSnapshot) GetAccess() *Access {
	if x != nil {
		return x.Access
	}
	return nil
}

// ContractUpstream represents an upstream for a contract
type ContractUpstream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractUpstream) Reset() {
	*x = ContractUpstream{}
	mi := &file_api_proto_v1_contract_syncer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractUpstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractUpstream) ProtoMessage() {}

func (x *ContractUpstream) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_contract_syncer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractUpstream.ProtoReflect.Descriptor instead.
func (*ContractUpstream) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_contract_syncer_proto_rawDescGZIP(), []int{3}
}

func (x *ContractUpstream) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Access represents access settings
type Access struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secure        bool                   `protobuf:"varint,1,opt,name=secure,proto3" json:"secure,omitempty"`
	Apps          []*App                 `protobuf:"bytes,2,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Access) Reset() {
	*x = Access{}
	mi := &file_api_proto_v1_contract_syncer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Access) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Access) ProtoMessage() {}

func (x *Access) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_contract_syncer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Access.ProtoReflect.Descriptor instead.
func (*Access) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_contract_syncer_proto_rawDescGZIP(), []int{4}
}

func (x *Access) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *Access) GetApps() []*App {
	if x != nil {
		return x.Apps
	}
	return nil
}

// App represents an application with access
type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Environments  []string               `protobuf:"bytes,2,rep,name=environments,proto3" json:"environments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_api_proto_v1_contract_syncer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_contract_syncer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_contract_syncer_proto_rawDescGZIP(), []int{5}
}

func (x *App) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *App) GetEnvironments() []string {
	if x != nil {
		return x.Environments
	}
	return nil
}

var File_api_proto_v1_contract_syncer_proto protoreflect.FileDescriptor

const file_api_proto_v1_contract_syncer_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/v1/contract_syncer.proto\x12\x16api.contract_syncer.v1\"S\n" +
	"\vSyncRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"l\n" +
	"\fSyncResponse\x12F\n" +
	"\tsnapshots\x18\x01 \x03(\v2(.api.contract_syncer.v1.ContractSnapshotR\tsnapshots\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xf4\x01\n" +
	"\x10ContractSnapshot\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12D\n" +
	"\bupstream\x18\x03 \x01(\v2(.api.contract_syncer.v1.ContractUpstreamR\bupstream\x126\n" +
	"\x17allow_undefined_methods\x18\x04 \x01(\bR\x15allowUndefinedMethods\x126\n" +
	"\x06access\x18\x05 \x01(\v2\x1e.api.contract_syncer.v1.AccessR\x06access\"&\n" +
	"\x10ContractUpstream\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"Q\n" +
	"\x06Access\x12\x16\n" +
	"\x06secure\x18\x01 \x01(\bR\x06secure\x12/\n" +
	"\x04apps\x18\x02 \x03(\v2\x1b.api.contract_syncer.v1.AppR\x04apps\"@\n" +
	"\x03App\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\"\n" +
	"\fenvironments\x18\x02 \x03(\tR\fenvironments2j\n" +
	"\x15ContractSyncerService\x12Q\n" +
	"\x04Sync\x12#.api.contract_syncer.v1.SyncRequest\x1a$.api.contract_syncer.v1.SyncResponseBMZKmerionyx/api-gateway/controller/pkg/api/contract_syncer/v1;contractsyncerv1b\x06proto3"

var (
	file_api_proto_v1_contract_syncer_proto_rawDescOnce sync.Once
	file_api_proto_v1_contract_syncer_proto_rawDescData []byte
)

func file_api_proto_v1_contract_syncer_proto_rawDescGZIP() []byte {
	file_api_proto_v1_contract_syncer_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_contract_syncer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_contract_syncer_proto_rawDesc), len(file_api_proto_v1_contract_syncer_proto_rawDesc)))
	})
	return file_api_proto_v1_contract_syncer_proto_rawDescData
}

var file_api_proto_v1_contract_syncer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_v1_contract_syncer_proto_goTypes = []any{
	(*SyncRequest)(nil),      // 0: api.contract_syncer.v1.SyncRequest
	(*SyncResponse)(nil),     // 1: api.contract_syncer.v1.SyncResponse
	(*ContractSnapshot)(nil), // 2: api.contract_syncer.v1.ContractSnapshot
	(*ContractUpstream)(nil), // 3: api.contract_syncer.v1.ContractUpstream
	(*Access)(nil),           // 4: api.contract_syncer.v1.Access
	(*App)(nil),              // 5: api.contract_syncer.v1.App
}
var file_api_proto_v1_contract_syncer_proto_depIdxs = []int32{
	2, // 0: api.contract_syncer.v1.SyncResponse.snapshots:type_name -> api.contract_syncer.v1.ContractSnapshot
	3, // 1: api.contract_syncer.v1.ContractSnapshot.upstream:type_name -> api.contract_syncer.v1.ContractUpstream
	4, // 2: api.contract_syncer.v1.ContractSnapshot.access:type_name -> api.contract_syncer.v1.Access
	5, // 3: api.contract_syncer.v1.Access.apps:type_name -> api.contract_syncer.v1.App
	0, // 4: api.contract_syncer.v1.ContractSyncerService.Sync:input_type -> api.contract_syncer.v1.SyncRequest
	1, // 5: api.contract_syncer.v1.ContractSyncerService.Sync:output_type -> api.contract_syncer.v1.SyncResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_v1_contract_syncer_proto_init() }
func file_api_proto_v1_contract_syncer_proto_init() {
	if File_api_proto_v1_contract_syncer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_contract_syncer_proto_rawDesc), len(file_api_proto_v1_contract_syncer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_contract_syncer_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_contract_syncer_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_contract_syncer_proto_msgTypes,
	}.Build()
	File_api_proto_v1_contract_syncer_proto = out.File
	file_api_proto_v1_contract_syncer_proto_goTypes = nil
	file_api_proto_v1_contract_syncer_proto_depIdxs = nil
}
