// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/proto/v1/contract_syncer.proto

package contractsyncerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContractSyncerService_Sync_FullMethodName = "/api.contract_syncer.v1.ContractSyncerService/Sync"
)

// ContractSyncerServiceClient is the client API for ContractSyncerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContractSyncerService service for synchronizing contracts
type ContractSyncerServiceClient interface {
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
}

type contractSyncerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContractSyncerServiceClient(cc grpc.ClientConnInterface) ContractSyncerServiceClient {
	return &contractSyncerServiceClient{cc}
}

func (c *contractSyncerServiceClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, ContractSyncerService_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractSyncerServiceServer is the server API for ContractSyncerService service.
// All implementations must embed UnimplementedContractSyncerServiceServer
// for forward compatibility.
//
// ContractSyncerService service for synchronizing contracts
type ContractSyncerServiceServer interface {
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
	mustEmbedUnimplementedContractSyncerServiceServer()
}

// UnimplementedContractSyncerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContractSyncerServiceServer struct{}

func (UnimplementedContractSyncerServiceServer) Sync(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedContractSyncerServiceServer) mustEmbedUnimplementedContractSyncerServiceServer() {}
func (UnimplementedContractSyncerServiceServer) testEmbeddedByValue()                               {}

// UnsafeContractSyncerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractSyncerServiceServer will
// result in compilation errors.
type UnsafeContractSyncerServiceServer interface {
	mustEmbedUnimplementedContractSyncerServiceServer()
}

func RegisterContractSyncerServiceServer(s grpc.ServiceRegistrar, srv ContractSyncerServiceServer) {
	// If the following call pancis, it indicates UnimplementedContractSyncerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContractSyncerService_ServiceDesc, srv)
}

func _ContractSyncerService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractSyncerServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractSyncerService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractSyncerServiceServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContractSyncerService_ServiceDesc is the grpc.ServiceDesc for ContractSyncerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContractSyncerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.contract_syncer.v1.ContractSyncerService",
	HandlerType: (*ContractSyncerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _ContractSyncerService_Sync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/contract_syncer.proto",
}
