// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: schemas.proto

package schemasv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "merionyx/api-gateway/pkg/api/contract/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncContractBundleRequest represents a request to sync a contract bundle
type SyncContractBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Bundle        string                 `protobuf:"bytes,3,opt,name=bundle,proto3" json:"bundle,omitempty"`
	Force         bool                   `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"` // Force synchronization even if already in etcd
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncContractBundleRequest) Reset() {
	*x = SyncContractBundleRequest{}
	mi := &file_schemas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncContractBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncContractBundleRequest) ProtoMessage() {}

func (x *SyncContractBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncContractBundleRequest.ProtoReflect.Descriptor instead.
func (*SyncContractBundleRequest) Descriptor() ([]byte, []int) {
	return file_schemas_proto_rawDescGZIP(), []int{0}
}

func (x *SyncContractBundleRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *SyncContractBundleRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *SyncContractBundleRequest) GetBundle() string {
	if x != nil {
		return x.Bundle
	}
	return ""
}

func (x *SyncContractBundleRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// SyncContractBundleResponse represents a response to sync a contract bundle
type SyncContractBundleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*v1.ContractSnapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	FromCache     bool                   `protobuf:"varint,2,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"` // true if taken from etcd, false if from Git
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncContractBundleResponse) Reset() {
	*x = SyncContractBundleResponse{}
	mi := &file_schemas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncContractBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncContractBundleResponse) ProtoMessage() {}

func (x *SyncContractBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncContractBundleResponse.ProtoReflect.Descriptor instead.
func (*SyncContractBundleResponse) Descriptor() ([]byte, []int) {
	return file_schemas_proto_rawDescGZIP(), []int{1}
}

func (x *SyncContractBundleResponse) GetSnapshots() []*v1.ContractSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *SyncContractBundleResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

// GetContractRequest represents a request to get a contract
type GetContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      string                 `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractRequest) Reset() {
	*x = GetContractRequest{}
	mi := &file_schemas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractRequest) ProtoMessage() {}

func (x *GetContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractRequest.ProtoReflect.Descriptor instead.
func (*GetContractRequest) Descriptor() ([]byte, []int) {
	return file_schemas_proto_rawDescGZIP(), []int{2}
}

func (x *GetContractRequest) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

// GetContractSnapshotRequest represents a request to get a contract snapshot
type GetContractSnapshotRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Repository string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Ref        string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Contract   string                 `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	// Bundle root path within the repo (same as environment config); empty means "." in etcd keys
	Path          string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractSnapshotRequest) Reset() {
	*x = GetContractSnapshotRequest{}
	mi := &file_schemas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractSnapshotRequest) ProtoMessage() {}

func (x *GetContractSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetContractSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_schemas_proto_rawDescGZIP(), []int{3}
}

func (x *GetContractSnapshotRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *GetContractSnapshotRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *GetContractSnapshotRequest) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *GetContractSnapshotRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// GetContractSnapshotResponse represents a response to get a contract snapshot
type GetContractSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *v1.ContractSnapshot   `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractSnapshotResponse) Reset() {
	*x = GetContractSnapshotResponse{}
	mi := &file_schemas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractSnapshotResponse) ProtoMessage() {}

func (x *GetContractSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetContractSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_schemas_proto_rawDescGZIP(), []int{4}
}

func (x *GetContractSnapshotResponse) GetSnapshot() *v1.ContractSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// ListContractSnapshotsRequest represents a request to list contract snapshots
type ListContractSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContractSnapshotsRequest) Reset() {
	*x = ListContractSnapshotsRequest{}
	mi := &file_schemas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContractSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContractSnapshotsRequest) ProtoMessage() {}

func (x *ListContractSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContractSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListContractSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_schemas_proto_rawDescGZIP(), []int{5}
}

func (x *ListContractSnapshotsRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ListContractSnapshotsRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *ListContractSnapshotsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ListContractSnapshotsResponse represents a response to list contract snapshots
type ListContractSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*v1.ContractSnapshot `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContractSnapshotsResponse) Reset() {
	*x = ListContractSnapshotsResponse{}
	mi := &file_schemas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContractSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContractSnapshotsResponse) ProtoMessage() {}

func (x *ListContractSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContractSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListContractSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_schemas_proto_rawDescGZIP(), []int{6}
}

func (x *ListContractSnapshotsResponse) GetSnapshots() []*v1.ContractSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

// SyncAllContractsRequest represents a request to sync all contracts
type SyncAllContractsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   string                 `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"` // If empty, sync all environments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAllContractsRequest) Reset() {
	*x = SyncAllContractsRequest{}
	mi := &file_schemas_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAllContractsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAllContractsRequest) ProtoMessage() {}

func (x *SyncAllContractsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAllContractsRequest.ProtoReflect.Descriptor instead.
func (*SyncAllContractsRequest) Descriptor() ([]byte, []int) {
	return file_schemas_proto_rawDescGZIP(), []int{7}
}

func (x *SyncAllContractsRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

// SyncAllContractsResponse represents a response to sync all contracts
type SyncAllContractsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncedCount   int32                  `protobuf:"varint,1,opt,name=synced_count,json=syncedCount,proto3" json:"synced_count,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAllContractsResponse) Reset() {
	*x = SyncAllContractsResponse{}
	mi := &file_schemas_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAllContractsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAllContractsResponse) ProtoMessage() {}

func (x *SyncAllContractsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAllContractsResponse.ProtoReflect.Descriptor instead.
func (*SyncAllContractsResponse) Descriptor() ([]byte, []int) {
	return file_schemas_proto_rawDescGZIP(), []int{8}
}

func (x *SyncAllContractsResponse) GetSyncedCount() int32 {
	if x != nil {
		return x.SyncedCount
	}
	return 0
}

func (x *SyncAllContractsResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_schemas_proto protoreflect.FileDescriptor

const file_schemas_proto_rawDesc = "" +
	"\n" +
	"\rschemas.proto\x12\x0eapi.schemas.v1\x1a\x14contract_types.proto\"{\n" +
	"\x19SyncContractBundleRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x16\n" +
	"\x06bundle\x18\x03 \x01(\tR\x06bundle\x12\x14\n" +
	"\x05force\x18\x04 \x01(\bR\x05force\"|\n" +
	"\x1aSyncContractBundleResponse\x12?\n" +
	"\tsnapshots\x18\x01 \x03(\v2!.api.contract.v1.ContractSnapshotR\tsnapshots\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x02 \x01(\bR\tfromCache\"0\n" +
	"\x12GetContractRequest\x12\x1a\n" +
	"\bcontract\x18\x01 \x01(\tR\bcontract\"~\n" +
	"\x1aGetContractSnapshotRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x1a\n" +
	"\bcontract\x18\x03 \x01(\tR\bcontract\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"\\\n" +
	"\x1bGetContractSnapshotResponse\x12=\n" +
	"\bsnapshot\x18\x01 \x01(\v2!.api.contract.v1.ContractSnapshotR\bsnapshot\"d\n" +
	"\x1cListContractSnapshotsRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"`\n" +
	"\x1dListContractSnapshotsResponse\x12?\n" +
	"\tsnapshots\x18\x01 \x03(\v2!.api.contract.v1.ContractSnapshotR\tsnapshots\";\n" +
	"\x17SyncAllContractsRequest\x12 \n" +
	"\venvironment\x18\x01 \x01(\tR\venvironment\"U\n" +
	"\x18SyncAllContractsResponse\x12!\n" +
	"\fsynced_count\x18\x01 \x01(\x05R\vsyncedCount\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors2\xca\x03\n" +
	"\x0eSchemasService\x12k\n" +
	"\x12SyncContractBundle\x12).api.schemas.v1.SyncContractBundleRequest\x1a*.api.schemas.v1.SyncContractBundleResponse\x12n\n" +
	"\x13GetContractSnapshot\x12*.api.schemas.v1.GetContractSnapshotRequest\x1a+.api.schemas.v1.GetContractSnapshotResponse\x12t\n" +
	"\x15ListContractSnapshots\x12,.api.schemas.v1.ListContractSnapshotsRequest\x1a-.api.schemas.v1.ListContractSnapshotsResponse\x12e\n" +
	"\x10SyncAllContracts\x12'.api.schemas.v1.SyncAllContractsRequest\x1a(.api.schemas.v1.SyncAllContractsResponseB>Z<merionyx/api-gateway/controller/pkg/api/schemas/v1;schemasv1b\x06proto3"

var (
	file_schemas_proto_rawDescOnce sync.Once
	file_schemas_proto_rawDescData []byte
)

func file_schemas_proto_rawDescGZIP() []byte {
	file_schemas_proto_rawDescOnce.Do(func() {
		file_schemas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemas_proto_rawDesc), len(file_schemas_proto_rawDesc)))
	})
	return file_schemas_proto_rawDescData
}

var file_schemas_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_schemas_proto_goTypes = []any{
	(*SyncContractBundleRequest)(nil),     // 0: api.schemas.v1.SyncContractBundleRequest
	(*SyncContractBundleResponse)(nil),    // 1: api.schemas.v1.SyncContractBundleResponse
	(*GetContractRequest)(nil),            // 2: api.schemas.v1.GetContractRequest
	(*GetContractSnapshotRequest)(nil),    // 3: api.schemas.v1.GetContractSnapshotRequest
	(*GetContractSnapshotResponse)(nil),   // 4: api.schemas.v1.GetContractSnapshotResponse
	(*ListContractSnapshotsRequest)(nil),  // 5: api.schemas.v1.ListContractSnapshotsRequest
	(*ListContractSnapshotsResponse)(nil), // 6: api.schemas.v1.ListContractSnapshotsResponse
	(*SyncAllContractsRequest)(nil),       // 7: api.schemas.v1.SyncAllContractsRequest
	(*SyncAllContractsResponse)(nil),      // 8: api.schemas.v1.SyncAllContractsResponse
	(*v1.ContractSnapshot)(nil),           // 9: api.contract.v1.ContractSnapshot
}
var file_schemas_proto_depIdxs = []int32{
	9, // 0: api.schemas.v1.SyncContractBundleResponse.snapshots:type_name -> api.contract.v1.ContractSnapshot
	9, // 1: api.schemas.v1.GetContractSnapshotResponse.snapshot:type_name -> api.contract.v1.ContractSnapshot
	9, // 2: api.schemas.v1.ListContractSnapshotsResponse.snapshots:type_name -> api.contract.v1.ContractSnapshot
	0, // 3: api.schemas.v1.SchemasService.SyncContractBundle:input_type -> api.schemas.v1.SyncContractBundleRequest
	3, // 4: api.schemas.v1.SchemasService.GetContractSnapshot:input_type -> api.schemas.v1.GetContractSnapshotRequest
	5, // 5: api.schemas.v1.SchemasService.ListContractSnapshots:input_type -> api.schemas.v1.ListContractSnapshotsRequest
	7, // 6: api.schemas.v1.SchemasService.SyncAllContracts:input_type -> api.schemas.v1.SyncAllContractsRequest
	1, // 7: api.schemas.v1.SchemasService.SyncContractBundle:output_type -> api.schemas.v1.SyncContractBundleResponse
	4, // 8: api.schemas.v1.SchemasService.GetContractSnapshot:output_type -> api.schemas.v1.GetContractSnapshotResponse
	6, // 9: api.schemas.v1.SchemasService.ListContractSnapshots:output_type -> api.schemas.v1.ListContractSnapshotsResponse
	8, // 10: api.schemas.v1.SchemasService.SyncAllContracts:output_type -> api.schemas.v1.SyncAllContractsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_schemas_proto_init() }
func file_schemas_proto_init() {
	if File_schemas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemas_proto_rawDesc), len(file_schemas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schemas_proto_goTypes,
		DependencyIndexes: file_schemas_proto_depIdxs,
		MessageInfos:      file_schemas_proto_msgTypes,
	}.Build()
	File_schemas_proto = out.File
	file_schemas_proto_goTypes = nil
	file_schemas_proto_depIdxs = nil
}
