apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- configmap-apps.yaml
- configmap-envoy.yaml
- rbac-controller-discovery.yaml
- services.yaml
- deployments.yaml
- deployment-envoy.yaml
