// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environments.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createEnvironment = `-- name: CreateEnvironment :exec
INSERT INTO control_plane.environments (uuid, name, config)
VALUES ($1, $2, $3)
`

type CreateEnvironmentParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	Name   string    `json:"name"`
	Config []byte    `json:"config"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) error {
	_, err := q.db.Exec(ctx, createEnvironment, arg.Uuid, arg.Name, arg.Config)
	return err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM control_plane.environments WHERE uuid = $1
`

func (q *Queries) DeleteEnvironment(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironment, argUuid)
	return err
}

const deleteEnvironmentListenerMappings = `-- name: DeleteEnvironmentListenerMappings :exec
DELETE FROM control_plane.listeners_environments WHERE environment_uuid = $1
`

func (q *Queries) DeleteEnvironmentListenerMappings(ctx context.Context, environmentUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentListenerMappings, environmentUuid)
	return err
}

const deleteEnvironmentTenantMappings = `-- name: DeleteEnvironmentTenantMappings :exec
DELETE FROM control_plane.tenants_environments WHERE environment_uuid = $1
`

func (q *Queries) DeleteEnvironmentTenantMappings(ctx context.Context, environmentUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentTenantMappings, environmentUuid)
	return err
}

const getEnvironmentByName = `-- name: GetEnvironmentByName :one
SELECT uuid, name, config FROM control_plane.environments WHERE name = $1
`

func (q *Queries) GetEnvironmentByName(ctx context.Context, name string) (ControlPlaneEnvironment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByName, name)
	var i ControlPlaneEnvironment
	err := row.Scan(&i.Uuid, &i.Name, &i.Config)
	return i, err
}

const getEnvironmentByUUID = `-- name: GetEnvironmentByUUID :one
SELECT uuid, name, config FROM control_plane.environments WHERE uuid = $1
`

func (q *Queries) GetEnvironmentByUUID(ctx context.Context, argUuid uuid.UUID) (ControlPlaneEnvironment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByUUID, argUuid)
	var i ControlPlaneEnvironment
	err := row.Scan(&i.Uuid, &i.Name, &i.Config)
	return i, err
}

const getEnvironments = `-- name: GetEnvironments :many
SELECT uuid, name, config FROM control_plane.environments
ORDER BY name
`

func (q *Queries) GetEnvironments(ctx context.Context) ([]ControlPlaneEnvironment, error) {
	rows, err := q.db.Query(ctx, getEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlPlaneEnvironment
	for rows.Next() {
		var i ControlPlaneEnvironment
		if err := rows.Scan(&i.Uuid, &i.Name, &i.Config); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentsByTenantUUID = `-- name: GetEnvironmentsByTenantUUID :many
SELECT e.uuid, e.name, e.config FROM control_plane.environments e
INNER JOIN control_plane.tenants_environments te ON e.uuid = te.environment_uuid
WHERE te.tenant_uuid = $1
ORDER BY e.name
`

func (q *Queries) GetEnvironmentsByTenantUUID(ctx context.Context, tenantUuid uuid.UUID) ([]ControlPlaneEnvironment, error) {
	rows, err := q.db.Query(ctx, getEnvironmentsByTenantUUID, tenantUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlPlaneEnvironment
	for rows.Next() {
		var i ControlPlaneEnvironment
		if err := rows.Scan(&i.Uuid, &i.Name, &i.Config); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mapTenantToEnvironment = `-- name: MapTenantToEnvironment :exec
INSERT INTO control_plane.tenants_environments (tenant_uuid, environment_uuid)
VALUES ($1, $2)
`

type MapTenantToEnvironmentParams struct {
	TenantUuid      uuid.UUID `json:"tenant_uuid"`
	EnvironmentUuid uuid.UUID `json:"environment_uuid"`
}

func (q *Queries) MapTenantToEnvironment(ctx context.Context, arg MapTenantToEnvironmentParams) error {
	_, err := q.db.Exec(ctx, mapTenantToEnvironment, arg.TenantUuid, arg.EnvironmentUuid)
	return err
}

const unmapTenantFromEnvironment = `-- name: UnmapTenantFromEnvironment :exec
DELETE FROM control_plane.tenants_environments 
WHERE tenant_uuid = $1 AND environment_uuid = $2
`

type UnmapTenantFromEnvironmentParams struct {
	TenantUuid      uuid.UUID `json:"tenant_uuid"`
	EnvironmentUuid uuid.UUID `json:"environment_uuid"`
}

func (q *Queries) UnmapTenantFromEnvironment(ctx context.Context, arg UnmapTenantFromEnvironmentParams) error {
	_, err := q.db.Exec(ctx, unmapTenantFromEnvironment, arg.TenantUuid, arg.EnvironmentUuid)
	return err
}

const updateEnvironment = `-- name: UpdateEnvironment :exec
UPDATE control_plane.environments SET name = $2, config = $3 WHERE uuid = $1
`

type UpdateEnvironmentParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	Name   string    `json:"name"`
	Config []byte    `json:"config"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) error {
	_, err := q.db.Exec(ctx, updateEnvironment, arg.Uuid, arg.Name, arg.Config)
	return err
}
