// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/google/uuid"
)

type ControlPlaneEnvironment struct {
	Uuid   uuid.UUID `json:"uuid"`
	Name   string    `json:"name"`
	Config []byte    `json:"config"`
}

type ControlPlaneListener struct {
	Uuid   uuid.UUID `json:"uuid"`
	Name   string    `json:"name"`
	Config []byte    `json:"config"`
}

type ControlPlaneListenersEnvironment struct {
	ListenerUuid    uuid.UUID `json:"listener_uuid"`
	EnvironmentUuid uuid.UUID `json:"environment_uuid"`
}

type ControlPlaneTenant struct {
	Uuid uuid.UUID `json:"uuid"`
	Name string    `json:"name"`
}

type ControlPlaneTenantsEnvironment struct {
	TenantUuid      uuid.UUID `json:"tenant_uuid"`
	EnvironmentUuid uuid.UUID `json:"environment_uuid"`
}

type SchemaMigration struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}
