// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :exec
INSERT INTO control_plane.tenants (uuid, name)
VALUES ($1, $2)
`

type CreateTenantParams struct {
	Uuid uuid.UUID `json:"uuid"`
	Name string    `json:"name"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.Exec(ctx, createTenant, arg.Uuid, arg.Name)
	return err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM control_plane.tenants WHERE uuid = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, argUuid)
	return err
}

const deleteTenantEnvironmentMappings = `-- name: DeleteTenantEnvironmentMappings :exec
DELETE FROM control_plane.tenants_environments WHERE tenant_uuid = $1
`

func (q *Queries) DeleteTenantEnvironmentMappings(ctx context.Context, tenantUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenantEnvironmentMappings, tenantUuid)
	return err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT uuid, name FROM control_plane.tenants WHERE name = $1
`

func (q *Queries) GetTenantByName(ctx context.Context, name string) (ControlPlaneTenant, error) {
	row := q.db.QueryRow(ctx, getTenantByName, name)
	var i ControlPlaneTenant
	err := row.Scan(&i.Uuid, &i.Name)
	return i, err
}

const getTenantByUUID = `-- name: GetTenantByUUID :one
SELECT uuid, name FROM control_plane.tenants WHERE uuid = $1
`

func (q *Queries) GetTenantByUUID(ctx context.Context, argUuid uuid.UUID) (ControlPlaneTenant, error) {
	row := q.db.QueryRow(ctx, getTenantByUUID, argUuid)
	var i ControlPlaneTenant
	err := row.Scan(&i.Uuid, &i.Name)
	return i, err
}

const getTenants = `-- name: GetTenants :many
SELECT uuid, name FROM control_plane.tenants
ORDER BY name
`

func (q *Queries) GetTenants(ctx context.Context) ([]ControlPlaneTenant, error) {
	rows, err := q.db.Query(ctx, getTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlPlaneTenant
	for rows.Next() {
		var i ControlPlaneTenant
		if err := rows.Scan(&i.Uuid, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :exec
UPDATE control_plane.tenants SET name = $2 WHERE uuid = $1
`

type UpdateTenantParams struct {
	Uuid uuid.UUID `json:"uuid"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) error {
	_, err := q.db.Exec(ctx, updateTenant, arg.Uuid, arg.Name)
	return err
}
