name: Publish Docker images to Docker Hub

permissions:
  contents: read
  packages: write

on:
  workflow_call:
    inputs:
      version:
        description: Docker image tag (latest, v1.0.0, ...)
        required: false
        type: string
        default: latest
      checkout_ref:
        description: Git ref (SHA) for checkout
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: Docker image tag (latest, v1.0.0, ...)
        required: false
        default: latest
        type: string

jobs:
  api-server:
    uses: ./.github/workflows/docker-publish-component.yml
    with:
      component: api-server
      dockerfile: build/release/Dockerfile.api-server
      checkout_ref: ${{ github.event_name == 'workflow_dispatch' && github.sha || inputs.checkout_ref }}
      version: ${{ inputs.version || 'latest' }}
    secrets: inherit

  auth-sidecar:
    uses: ./.github/workflows/docker-publish-component.yml
    with:
      component: auth-sidecar
      dockerfile: build/release/Dockerfile.auth-sidecar
      checkout_ref: ${{ github.event_name == 'workflow_dispatch' && github.sha || inputs.checkout_ref }}
      version: ${{ inputs.version || 'latest' }}
    secrets: inherit

  contract-syncer:
    uses: ./.github/workflows/docker-publish-component.yml
    with:
      component: contract-syncer
      dockerfile: build/release/Dockerfile.contract-syncer
      checkout_ref: ${{ github.event_name == 'workflow_dispatch' && github.sha || inputs.checkout_ref }}
      version: ${{ inputs.version || 'latest' }}
    secrets: inherit

  controller:
    uses: ./.github/workflows/docker-publish-component.yml
    with:
      component: controller
      dockerfile: build/release/Dockerfile.controller
      checkout_ref: ${{ github.event_name == 'workflow_dispatch' && github.sha || inputs.checkout_ref }}
      version: ${{ inputs.version || 'latest' }}
    secrets: inherit
