name: Publish Docker images to Docker Hub

on:
  push:
    branches:
    - main

jobs:
  api-server:
    uses: ./.github/workflows/docker-publish-component.yml
    with:
      component: api-server
      dockerfile: build/release/Dockerfile.api-server
    secrets: inherit

  auth-sidecar:
    uses: ./.github/workflows/docker-publish-component.yml
    with:
      component: auth-sidecar
      dockerfile: build/release/Dockerfile.auth-sidecar
    secrets: inherit

  contract-syncer:
    uses: ./.github/workflows/docker-publish-component.yml
    with:
      component: contract-syncer
      dockerfile: build/release/Dockerfile.contract-syncer
    secrets: inherit

  controller:
    uses: ./.github/workflows/docker-publish-component.yml
    with:
      component: controller
      dockerfile: build/release/Dockerfile.controller
    secrets: inherit

  mock-service:
    uses: ./.github/workflows/docker-publish-component.yml
    with:
      component: mock-service
      dockerfile: build/dev/Dockerfile.mock-service
    secrets: inherit
